import subprocess, json, os, tempfile

os.environ['PYTHONIOENCODING'] = 'utf-8'
GWS = r'C:\Users\linkang\AppData\Roaming\npm\gws.cmd'
SPREADSHEET_ID = '11BIizMMOQRWzLZi9TjvxDxn_i0949wKwMX-T9_zlYTY'
TARGET_SHEET = 'ITEM'

start_id = 1011144257

rows = [
    [start_id, '111110301', '极速飞车主题卡包', 'Speed Racing Theme Card Pack', 'Pack de cartes thematique Course de vitesse', 'Hochgeschwindigkeitsrennen-Themenkartenpaket', 'Pacote de Cartas Tematico Corrida Veloz', '極速飛車主題卡包', 'Paket Kartu Tema Balap Kecepatan', 'แพ็คการ์ดธีมแข่งรถความเร็ว', 'Paquete de Cartas Tematico Carrera de Velocidad', 'Тематический набор карт Скоростные гонки', 'Hiz Yarisi Tema Kart Paketi', 'Goi The Chu De Dua Xe Toc Do', 'Pacchetto Carte Tema Corsa Veloce', 'Paczka Kart Tematycznych Wyscigi Predkosci', 'حزمة بطاقات سباق السرعة الموضوعية', 'スピードレーシングテーマカードパック', '스피드 레이싱 테마 카드팩', '极速飞车主题卡包'],
    [start_id+1, '111110302', '矿洞寻宝主题卡包', 'Mine Treasure Hunt Theme Card Pack', 'Pack de cartes thematique Chasse au tresor minier', 'Minenschatzsuche-Themenkartenpaket', 'Pacote de Cartas Tematico Caca ao Tesouro na Mina', '礦洞尋寶主題卡包', 'Paket Kartu Tema Berburu Harta Karun Tambang', 'แพ็คการ์ดธีมล่าสมบัติเหมือง', 'Paquete de Cartas Tematico Busqueda del Tesoro Minero', 'Тематический набор карт Охота за сокровищами в шахте', 'Maden Hazine Avi Tema Kart Paketi', 'Goi The Chu De San Kho Bau Ham Mo', 'Pacchetto Carte Tema Caccia al Tesoro Minerario', 'Paczka Kart Tematycznych Poszukiwanie Skarbow w Kopalni', 'حزمة بطاقات البحث عن الكنز في المنجم الموضوعية', '鉱山トレジャーハントテーマカードパック', '광산 보물찾기 테마 카드팩', '矿洞寻宝主题卡包'],
    [start_id+2, '111110303', '彩蛋大亨主题卡包', 'Easter Tycoon Theme Card Pack', 'Pack de cartes thematique Magnat de Paques', 'Oster-Tycoon-Themenkartenpaket', 'Pacote de Cartas Tematico Magnata da Pascoa', '彩蛋大亨主題卡包', 'Paket Kartu Tema Taipan Paskah', 'แพ็คการ์ดธีมเศรษฐีอีสเตอร์', 'Paquete de Cartas Tematico Magnate de Pascua', 'Тематический набор карт Пасхальный магнат', 'Paskalya Kodamani Tema Kart Paketi', 'Goi The Chu De Dai Gia Phuc Sinh', 'Pacchetto Carte Tema Magnate di Pasqua', 'Paczka Kart Tematycznych Wielkanocny Potentat', 'حزمة بطاقات قطب عيد الفصح الموضوعية', 'イースタータイクーンテーマカードパック', '이스터 타이쿤 테마 카드팩', '彩蛋大亨主题卡包'],
    [start_id+3, '111110304', '异族探秘主题卡包', 'Alien Exploration Theme Card Pack', 'Pack de cartes thematique Exploration extraterrestre', 'Alien-Erkundungs-Themenkartenpaket', 'Pacote de Cartas Tematico Exploracao Alienigena', '異族探秘主題卡包', 'Paket Kartu Tema Eksplorasi Alien', 'แพ็คการ์ดธีมสำรวจเอเลี่ยน', 'Paquete de Cartas Tematico Exploracion Alienigena', 'Тематический набор карт Исследование инопланетян', 'Uzayli Kesfi Tema Kart Paketi', 'Goi The Chu De Kham Pha Nguoi Ngoai Hanh Tinh', 'Pacchetto Carte Tema Esplorazione Aliena', 'Paczka Kart Tematycznych Eksploracja Obcych', 'حزمة بطاقات استكشاف الفضائيين الموضوعية', 'エイリアン探検テーマカードパック', '외계인 탐험 테마 카드팩', '异族探秘主题卡包'],
    [start_id+4, '111110305', '节日白色保底卡包-复活节', 'Festival White Guaranteed Card Pack - Easter', 'Pack de cartes garanti blanc festival - Paques', 'Festival Weiss Garantiertes Kartenpaket - Ostern', 'Pacote de Cartas Garantido Branco Festival - Pascoa', '節日白色保底卡包-復活節', 'Paket Kartu Jaminan Putih Festival - Paskah', 'แพ็คการ์ดการันตีสีขาวเทศกาล - อีสเตอร์', 'Paquete de Cartas Garantizado Blanco Festival - Pascua', 'Праздничный белый гарантированный набор карт - Пасха', 'Festival Beyaz Garantili Kart Paketi - Paskalya', 'Goi The Dam Bao Trang Le Hoi - Phuc Sinh', 'Pacchetto Carte Garantito Bianco Festival - Pasqua', 'Paczka Kart Gwarantowanych Biala Swiateczna - Wielkanoc', 'حزمة بطاقات مضمونة بيضاء للمهرجان - عيد الفصح', 'フェスティバルホワイト確定カードパック - イースター', '축제 화이트 확정 카드팩 - 부활절', '节日白色保底卡包-复活节'],
    [start_id+5, '111110306', '节日绿色保底卡包-复活节', 'Festival Green Guaranteed Card Pack - Easter', 'Pack de cartes garanti vert festival - Paques', 'Festival Grun Garantiertes Kartenpaket - Ostern', 'Pacote de Cartas Garantido Verde Festival - Pascoa', '節日綠色保底卡包-復活節', 'Paket Kartu Jaminan Hijau Festival - Paskah', 'แพ็คการ์ดการันตีสีเขียวเทศกาล - อีสเตอร์', 'Paquete de Cartas Garantizado Verde Festival - Pascua', 'Праздничный зеленый гарантированный набор карт - Пасха', 'Festival Yesil Garantili Kart Paketi - Paskalya', 'Goi The Dam Bao Xanh La Le Hoi - Phuc Sinh', 'Pacchetto Carte Garantito Verde Festival - Pasqua', 'Paczka Kart Gwarantowanych Zielona Swiateczna - Wielkanoc', 'حزمة بطاقات مضمونة خضراء للمهرجان - عيد الفصح', 'フェスティバルグリーン確定カードパック - イースター', '축제 그린 확정 카드팩 - 부활절', '节日绿色保底卡包-复活节'],
    [start_id+6, '111110307', '节日蓝色保底卡包-复活节', 'Festival Blue Guaranteed Card Pack - Easter', 'Pack de cartes garanti bleu festival - Paques', 'Festival Blau Garantiertes Kartenpaket - Ostern', 'Pacote de Cartas Garantido Azul Festival - Pascoa', '節日藍色保底卡包-復活節', 'Paket Kartu Jaminan Biru Festival - Paskah', 'แพ็คการ์ดการันตีสีน้ำเงินเทศกาล - อีสเตอร์', 'Paquete de Cartas Garantizado Azul Festival - Pascua', 'Праздничный синий гарантированный набор карт - Пасха', 'Festival Mavi Garantili Kart Paketi - Paskalya', 'Goi The Dam Bao Xanh Duong Le Hoi - Phuc Sinh', 'Pacchetto Carte Garantito Blu Festival - Pasqua', 'Paczka Kart Gwarantowanych Niebieska Swiateczna - Wielkanoc', 'حزمة بطاقات مضمونة زرقاء للمهرجان - عيد الفصح', 'フェスティバルブルー確定カードパック - イースター', '축제 블루 확정 카드팩 - 부활절', '节日蓝色保底卡包-复活节'],
    [start_id+7, '111110308', '节日紫色保底卡包-复活节', 'Festival Purple Guaranteed Card Pack - Easter', 'Pack de cartes garanti violet festival - Paques', 'Festival Lila Garantiertes Kartenpaket - Ostern', 'Pacote de Cartas Garantido Roxo Festival - Pascoa', '節日紫色保底卡包-復活節', 'Paket Kartu Jaminan Ungu Festival - Paskah', 'แพ็คการ์ดการันตีสีม่วงเทศกาล - อีสเตอร์', 'Paquete de Cartas Garantizado Purpura Festival - Pascua', 'Праздничный фиолетовый гарантированный набор карт - Пасха', 'Festival Mor Garantili Kart Paketi - Paskalya', 'Goi The Dam Bao Tim Le Hoi - Phuc Sinh', 'Pacchetto Carte Garantito Viola Festival - Pasqua', 'Paczka Kart Gwarantowanych Fioletowa Swiateczna - Wielkanoc', 'حزمة بطاقات مضمونة بنفسجية للمهرجان - عيد الفصح', 'フェスティバルパープル確定カードパック - イースター', '축제 퍼플 확정 카드팩 - 부활절', '节日紫色保底卡包-复活节'],
    [start_id+8, '111110309', '节日橙色保底卡包-复活节', 'Festival Orange Guaranteed Card Pack - Easter', 'Pack de cartes garanti orange festival - Paques', 'Festival Orange Garantiertes Kartenpaket - Ostern', 'Pacote de Cartas Garantido Laranja Festival - Pascoa', '節日橙色保底卡包-復活節', 'Paket Kartu Jaminan Oranye Festival - Paskah', 'แพ็คการ์ดการันตีสีส้มเทศกาล - อีสเตอร์', 'Paquete de Cartas Garantizado Naranja Festival - Pascua', 'Праздничный оранжевый гарантированный набор карт - Пасха', 'Festival Turuncu Garantili Kart Paketi - Paskalya', 'Goi The Dam Bao Cam Le Hoi - Phuc Sinh', 'Pacchetto Carte Garantito Arancione Festival - Pasqua', 'Paczka Kart Gwarantowanych Pomaranczowa Swiateczna - Wielkanoc', 'حزمة بطاقات مضمونة برتقالية للمهرجان - عيد الفصح', 'フェスティバルオレンジ確定カードパック - イースター', '축제 오렌지 확정 카드팩 - 부활절', '节日橙色保底卡包-复活节'],
    [start_id+9, '111111023', '节日自选卡包-四星以上-复活节', 'Festival Custom Card Pack - 4 Stars or Above - Easter', 'Pack de cartes personnalise festival - 4 etoiles ou plus - Paques', 'Festival Auswahl-Kartenpaket - 4 Sterne oder hoher - Ostern', 'Pacote de Cartas Personalizado Festival - 4 Estrelas ou Mais - Pascoa', '節日自選卡包-四星以上-復活節', 'Paket Kartu Pilihan Festival - 4 Bintang atau Lebih - Paskah', 'แพ็คการ์ดเลือกเองเทศกาล - 4 ดาวขึ้นไป - อีสเตอร์', 'Paquete de Cartas Personalizado Festival - 4 Estrellas o Mas - Pascua', 'Праздничный набор карт на выбор - 4 звезды и выше - Пасха', 'Festival Secim Kart Paketi - 4 Yildiz ve Uzeri - Paskalya', 'Goi The Tu Chon Le Hoi - 4 Sao Tro Len - Phuc Sinh', 'Pacchetto Carte Personalizzato Festival - 4 Stelle o Superiori - Pasqua', 'Paczka Kart Do Wyboru Swiateczna - 4 Gwiazdki lub Wiecej - Wielkanoc', 'حزمة بطاقات مخصصة للمهرجان - 4 نجوم أو أكثر - عيد الفصح', 'フェスティバルカスタムカードパック - 4つ星以上 - イースター', '축제 선택 카드팩 - 4성 이상 - 부활절', '节日自选卡包-四星以上-复活节'],
    [start_id+10, '111111024', '2026复活节集卡册静态头像框', '2026 Easter Card Album Static Avatar Frame', 'Cadre d avatar statique Album de cartes Paques 2026', '2026 Ostern Kartenalbum Statischer Avatarrahmen', 'Moldura de Avatar Estatica Album de Cartas Pascoa 2026', '2026復活節集卡冊靜態頭像框', 'Bingkai Avatar Statis Album Kartu Paskah 2026', 'กรอบอวาตาร์คงที่อัลบั้มการ์ดอีสเตอร์ 2026', 'Marco de Avatar Estatico Album de Cartas Pascua 2026', 'Статическая рамка аватара Альбом карт Пасха 2026', '2026 Paskalya Kart Albumu Statik Avatar Cercevesi', 'Khung Avatar Tinh Album The Phuc Sinh 2026', 'Cornice Avatar Statica Album Carte Pasqua 2026', 'Statyczna Ramka Awatara Album Kart Wielkanoc 2026', 'إطار صورة رمزية ثابت ألبوم بطاقات عيد الفصح 2026', '2026イースターカードアルバム静的アバターフレーム', '2026 부활절 카드 앨범 정적 아바타 프레임', '2026复活节集卡册静态头像框'],
]

with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False, encoding='utf-8') as f:
    json.dump({'values': rows}, f, ensure_ascii=False)
    temp_file = f.name

append_params = json.dumps({
    'spreadsheetId': SPREADSHEET_ID,
    'range': f'{TARGET_SHEET}!A1',
    'valueInputOption': 'RAW',
    'insertDataOption': 'INSERT_ROWS',
})

with open(temp_file, 'r', encoding='utf-8') as f:
    body_json = f.read()

result = subprocess.run(
    [GWS, 'sheets', 'spreadsheets', 'values', 'append',
     '--params', append_params,
     '--json', body_json],
    capture_output=True, shell=True
)
print(result.stdout.decode('utf-8', errors='replace'))
os.unlink(temp_file)
