
with open('C:/Users/linkang/mining_saturation_report.html', 'r', encoding='utf-8') as f:
    html = f.read()

# Remove the hidden placeholder
PLACEHOLDER = '  <div class="sec-title" style="margin-top:8px;display:none">具体配置改动清单_MOVED</div>'
html = html.replace(PLACEHOLDER, '', 1)
print('Removed placeholder')

ANCHOR = '  <div class="sec-title" style="margin-top:8px">各渠道优化方向</div>'

NEW_SECTION = (
    '  <div class="sec-title" style="margin-top:8px">具体配置改动清单</div>\n'
    '  <div style="font-size:12px;color:var(--text2);margin-bottom:16px">以下为有实质变化的配置项，标注道具ID + 位置 + 改动量 + 加法理由；维持不动的渠道不列出</div>\n\n'
    '  <!-- 改动1 -->\n'
    '  <div style="background:var(--bg2);border:1px solid var(--border);border-radius:8px;margin-bottom:12px;overflow:hidden">\n'
    '    <div style="padding:12px 16px;background:rgba(57,255,138,.06);border-bottom:1px solid var(--border);display:flex;align-items:center;gap:12px">\n'
    '      <span style="font-family:var(--mono);font-size:11px;background:rgba(57,255,138,.15);color:var(--ok);padding:3px 10px;border-radius:3px">改动 #1</span>\n'
    '      <span style="font-size:14px;font-weight:700;color:#fff">每日/7日签到奖励 · 绿包前移</span>\n'
    '      <span style="margin-left:auto;font-family:var(--mono);font-size:11px;color:var(--ok)">活动 21127574 · 道具 <strong>111110003</strong> · +7个</span>\n'
    '    </div>\n'
    '    <div style="padding:14px 16px;display:grid;grid-template-columns:1fr 1fr;gap:16px">\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--text2);letter-spacing:2px;margin-bottom:8px">当前配置（问题）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          Day 1-9：每日奖励只有 <span style="color:#60c8ff">白包(111110002)</span>x1 + 其他道具<br>\n'
    '          Day 10+：才开始出现 <span style="color:#39ff8a">绿包(111110003)</span><br>\n'
    '          签到 1-9 天的玩家（含0-5天组 3,383人）<strong style="color:var(--danger)">整个节日零绿包</strong>\n'
    '        </div>\n'
    '      </div>\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--ok);letter-spacing:2px;margin-bottom:8px">目标配置（改动）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          Day 1：白x1 + <span style="color:var(--ok)">绿(111110003)x1（新增）</span><br>\n'
    '          Day 3：白x1 + <span style="color:var(--ok)">绿x1（新增）</span><br>\n'
    '          Day 5：白x1 + <span style="color:var(--ok)">绿x1（新增）</span><br>\n'
    '          Day 7：白x1 → <span style="color:var(--ok)">绿x1（替换）</span><br>\n'
    '          Day 9：白x1 → <span style="color:var(--ok)">绿x1（替换）</span><br>\n'
    '          Day 10+：维持现有 3-5 绿包（不变）\n'
    '        </div>\n'
    '      </div>\n'
    '      <div style="grid-column:1/-1;background:var(--bg3);border-radius:5px;padding:10px 14px;font-size:12px;color:var(--text2)">\n'
    '        <strong style="color:var(--warn)">理由：</strong>绿包(111110003)是2★池卡片的主要来源（84%概率），中等活跃玩家2★池严重偏低的根本原因是绿包前9天完全空缺。每日签到触达14,910人，前移绿包成本最低、覆盖最广，单次改动收益最大。\n'
    '      </div>\n'
    '    </div>\n'
    '  </div>\n\n'
    '  <!-- 改动2 -->\n'
    '  <div style="background:var(--bg2);border:1px solid var(--border);border-radius:8px;margin-bottom:12px;overflow:hidden">\n'
    '    <div style="padding:12px 16px;background:rgba(57,255,138,.06);border-bottom:1px solid var(--border);display:flex;align-items:center;gap:12px">\n'
    '      <span style="font-family:var(--mono);font-size:11px;background:rgba(57,255,138,.15);color:var(--ok);padding:3px 10px;border-radius:3px">改动 #2</span>\n'
    '      <span style="font-size:14px;font-weight:700;color:#fff">BINGO连线奖励 · 新增绿包连线</span>\n'
    '      <span style="margin-left:auto;font-family:var(--mono);font-size:11px;color:var(--ok)">活动 21127035 · 111110003 +7 | 111110002 +3</span>\n'
    '    </div>\n'
    '    <div style="padding:14px 16px;display:grid;grid-template-columns:1fr 1fr;gap:16px">\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--text2);letter-spacing:2px;margin-bottom:8px">当前配置（问题）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          右1/右2/右3/下1/下2/下3 = <span style="color:#60c8ff">白x2</span>（无绿包）<br>\n'
    '          右4/下4 = 含16号充值格，绿包集中在此<br>\n'
    '          不充值的玩家，9条连线中 <strong style="color:var(--danger)">7条完全没有绿包</strong><br>\n'
    '          BINGO实际绿包产出：人均仅 0.9 个（设计5个）\n'
    '        </div>\n'
    '      </div>\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--ok);letter-spacing:2px;margin-bottom:8px">目标配置（改动）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          右1：白x2 → <span style="color:var(--ok)">白x3+绿x1</span>（+1白+1绿）<br>\n'
    '          右2：白x2 → <span style="color:var(--ok)">白x2+绿x1</span>（+1绿）<br>\n'
    '          右3：白x2 → <span style="color:var(--ok)">白x2+绿x1</span>（+1绿）<br>\n'
    '          下1：白x2 → <span style="color:var(--ok)">白x3+绿x1</span>（+1白+1绿）<br>\n'
    '          下2：白x2 → <span style="color:var(--ok)">白x2+绿x1</span>（+1绿）<br>\n'
    '          下3：白x2 → <span style="color:var(--ok)">白x2+绿x1</span>（+1绿）<br>\n'
    '          斜线：白x2 → <span style="color:var(--ok)">白x2+绿x1</span>（+1绿）<br>\n'
    '          右4/下4：维持（含充值格，绿包已合理）\n'
    '        </div>\n'
    '      </div>\n'
    '      <div style="grid-column:1/-1;background:var(--bg3);border-radius:5px;padding:10px 14px;font-size:12px;color:var(--text2)">\n'
    '        <strong style="color:var(--warn)">理由：</strong>BINGO连线触达7,334-9,528人，是最高覆盖的自由渠道。当前不含充值格的7条连线全为纯白包，非付费玩家几乎拿不到绿包。7条连线各+1绿（+斜线），每个完成BINGO的玩家多获7绿包，受益人数~7,000-9,000人。右1/下1各+1白维持奖励密度。\n'
    '      </div>\n'
    '    </div>\n'
    '  </div>\n\n'
    '  <!-- 改动3 -->\n'
    '  <div style="background:var(--bg2);border:1px solid var(--border);border-radius:8px;margin-bottom:12px;overflow:hidden">\n'
    '    <div style="padding:12px 16px;background:rgba(57,255,138,.06);border-bottom:1px solid var(--border);display:flex;align-items:center;gap:12px">\n'
    '      <span style="font-family:var(--mono);font-size:11px;background:rgba(57,255,138,.15);color:var(--ok);padding:3px 10px;border-radius:3px">改动 #3 · P0</span>\n'
    '      <span style="font-size:14px;font-weight:700;color:#fff">卡包BP免费段 · 绿包前移至前10级</span>\n'
    '      <span style="margin-left:auto;font-family:var(--mono);font-size:11px;color:var(--ok)">活动 21127547 · 道具 <strong>111110003</strong> · 零新增成本替换</span>\n'
    '    </div>\n'
    '    <div style="padding:14px 16px;display:grid;grid-template-columns:1fr 1fr;gap:16px">\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--text2);letter-spacing:2px;margin-bottom:8px">当前配置（问题）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          L1-10 免费：全部为 <span style="color:#60c8ff">白包(111110002)</span>x1 或加速道具<br>\n'
    '          L11-17 免费：<span style="color:#39ff8a">绿包(111110003)</span>x1 出现（共4个）<br>\n'
    '          需积累 1000 BP（约Day 4）才能拿到第一个绿包<br>\n'
    '          低活跃玩家（0-5天）几乎拿不到任何绿包\n'
    '        </div>\n'
    '      </div>\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--ok);letter-spacing:2px;margin-bottom:8px">目标配置（改动）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          L5 免费：白x1 → <span style="color:var(--ok)">绿(111110003)x1</span>（替换）<br>\n'
    '          L7 免费：白x1 → <span style="color:var(--ok)">绿(111110003)x1</span>（替换）<br>\n'
    '          L9 免费：白x1 → <span style="color:var(--ok)">绿(111110003)x1</span>（替换）<br>\n'
    '          L11-17：维持原4个绿包 → 共7个免费绿包<br>\n'
    '          L5 仅需500 BP（约Day 2）即可拿到第一绿包\n'
    '        </div>\n'
    '      </div>\n'
    '      <div style="grid-column:1/-1;background:var(--bg3);border-radius:5px;padding:10px 14px;font-size:12px;color:var(--text2)">\n'
    '        <strong style="color:var(--warn)">理由：</strong>L5/7/9白包在2-3天内玩家已轻松拿到，改为绿包白包总量减少3个（不影响白包饱和度），换来绿包时间前移2-3天。总包量不变，仅调整品质分布，是零成本的结构优化，P0优先级最高。\n'
    '      </div>\n'
    '    </div>\n'
    '  </div>\n\n'
    '  <!-- 改动4 -->\n'
    '  <div style="background:var(--bg2);border:1px solid var(--border);border-radius:8px;margin-bottom:12px;overflow:hidden">\n'
    '    <div style="padding:12px 16px;background:rgba(0,212,255,.06);border-bottom:1px solid var(--border);display:flex;align-items:center;gap:12px">\n'
    '      <span style="font-family:var(--mono);font-size:11px;background:rgba(0,212,255,.15);color:var(--accent);padding:3px 10px;border-radius:3px">改动 #4</span>\n'
    '      <span style="font-size:14px;font-weight:700;color:#fff">挖矿固定关 · 前置白包降低推进门槛</span>\n'
    '      <span style="margin-left:auto;font-family:var(--mono);font-size:11px;color:var(--accent)">活动 21127656 · 道具 <strong>111110002</strong> · +10个</span>\n'
    '    </div>\n'
    '    <div style="padding:14px 16px;display:grid;grid-template-columns:1fr 1fr;gap:16px">\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--text2);letter-spacing:2px;margin-bottom:8px">当前配置（问题）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          固定关 1-1→4-2 白包奖励稀少，集中在深层关卡<br>\n'
    '          1-1触达55.9% → 2-1触达32.3%（掉落23pp）<br>\n'
    '          2-2触达20% → 进入循环关只有 <strong style="color:var(--danger)">17%</strong><br>\n'
    '          固定关段缺乏推进动力，卡在1-2到2-1之间\n'
    '        </div>\n'
    '      </div>\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--ok);letter-spacing:2px;margin-bottom:8px">目标配置（改动）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          1-1节点完成：+<span style="color:var(--accent)">白(111110002)x3</span><br>\n'
    '          2-1节点完成：+<span style="color:var(--accent)">白(111110002)x3</span><br>\n'
    '          2-2节点完成：+<span style="color:var(--accent)">白(111110002)x4</span><br>\n'
    '          循环关入口（78_1）触达率目标：17% → 40%+<br>\n'
    '          （需同时降低1-2到2-1的矿石门槛）\n'
    '        </div>\n'
    '      </div>\n'
    '      <div style="grid-column:1/-1;background:var(--bg3);border-radius:5px;padding:10px 14px;font-size:12px;color:var(--text2)">\n'
    '        <strong style="color:var(--warn)">理由：</strong>挖矿是白包最大自由渠道，但循环关才是核心产出，触达率只有17%。在1-1/2-1/2-2三个漏斗节点加白包，给玩家推进动力；+10白包配合78_2难度优化，目标循环关触达率17%→40%，届时白包产量随触达率大幅提升。\n'
    '      </div>\n'
    '    </div>\n'
    '  </div>\n\n'
    '  <!-- 改动5 -->\n'
    '  <div style="background:var(--bg2);border:1px solid var(--border);border-radius:8px;margin-bottom:12px;overflow:hidden">\n'
    '    <div style="padding:12px 16px;background:rgba(57,255,138,.06);border-bottom:1px solid var(--border);display:flex;align-items:center;gap:12px">\n'
    '      <span style="font-family:var(--mono);font-size:11px;background:rgba(57,255,138,.15);color:var(--ok);padding:3px 10px;border-radius:3px">改动 #5 · P0</span>\n'
    '      <span style="font-size:14px;font-weight:700;color:#fff">挖矿循环关 · 绿包从排行榜改为关卡完成奖励</span>\n'
    '      <span style="margin-left:auto;font-family:var(--mono);font-size:11px;color:var(--ok)">活动 21127656 · 道具 <strong>111110003</strong> · 排行榜→免费（总量不变）</span>\n'
    '    </div>\n'
    '    <div style="padding:14px 16px;display:grid;grid-template-columns:1fr 1fr;gap:16px">\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--text2);letter-spacing:2px;margin-bottom:8px">当前配置（问题）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          循环关绿包(111110003) 36个：全部为<strong style="color:var(--danger)">排行榜奖励</strong><br>\n'
    '          只有排行榜前N名（高活跃/付费）能获得<br>\n'
    '          普通玩家即使完成循环关 <strong style="color:var(--danger)">也拿不到任何绿包</strong><br>\n'
    '          挖矿对中等活跃玩家的绿包贡献 = 0\n'
    '        </div>\n'
    '      </div>\n'
    '      <div>\n'
    '        <div style="font-family:var(--mono);font-size:10px;color:var(--ok);letter-spacing:2px;margin-bottom:8px">目标配置（改动）</div>\n'
    '        <div style="font-size:12px;color:var(--text2);line-height:1.9">\n'
    '          79_2 完成奖励：+<span style="color:var(--ok)">绿(111110003)x1</span>（从排行榜移出）<br>\n'
    '          80_1 完成奖励：+<span style="color:var(--ok)">绿x1</span><br>\n'
    '          80_2 完成奖励：+<span style="color:var(--ok)">绿x1</span><br>\n'
    '          80_3 完成奖励：+<span style="color:var(--ok)">绿x1</span><br>\n'
    '          81_1 完成奖励：+<span style="color:var(--ok)">绿x1</span><br>\n'
    '          81_2 完成奖励：+<span style="color:var(--ok)">绿x1</span><br>\n'
    '          排行榜：减少对应绿包，用其他道具补位\n'
    '        </div>\n'
    '      </div>\n'
    '      <div style="grid-column:1/-1;background:var(--bg3);border-radius:5px;padding:10px 14px;font-size:12px;color:var(--text2)">\n'
    '        <strong style="color:var(--warn)">理由：</strong>5条改动中性价比最高——<strong style="color:var(--ok)">总绿包量不变，只改分发方式</strong>。当前触达循环关的17%玩家（约6,000-8,500人/期）拼完关卡却全无绿包，体验极差。改为关卡完成奖励后，这批玩家每刷一轮获得6绿包，形成"越打越有"正向循环，同时激励玩家推进更深节点。\n'
    '      </div>\n'
    '    </div>\n'
    '  </div>\n\n'
    '  <div style="background:var(--bg3);border-radius:6px;padding:14px 16px;font-size:12px;color:var(--text2);line-height:1.9;margin-bottom:24px">\n'
    '    <strong style="color:var(--accent);font-family:var(--mono);font-size:10px;letter-spacing:2px">改动优先级</strong><br>\n'
    '    <span style="color:var(--ok)">P0（零新增成本，立即可做）：</span>#3 BP绿包前移（品质替换）、#5 挖矿循环绿包排行榜→免费（总量不变）<br>\n'
    '    <span style="color:var(--warn)">P1（需调整配置数值）：</span>#1 每日签到绿包前移+7、#2 BINGO连线增绿包+白包<br>\n'
    '    <span style="color:var(--accent2)">P2（需结合关卡难度调整）：</span>#4 挖矿固定关+白包+降门槛，需策划同步评估78_2难度\n'
    '  </div>\n\n'
)

if ANCHOR in html:
    html = html.replace(ANCHOR, NEW_SECTION + ANCHOR, 1)
    print('Inserted section before anchor')
else:
    print('ERROR: anchor not found')

with open('C:/Users/linkang/mining_saturation_report.html', 'w', encoding='utf-8') as f:
    f.write(html)
print('Done. File size:', len(html))
