"""
拓荒节集卡册 i18n 直接写入脚本
EVENT tab: 80条（8组名 + 72卡名）
ITEM tab:  22条（11包名 + 11包描述）
"""
import subprocess, json, os

os.environ['GOOGLE_WORKSPACE_PROJECT_ID'] = 'calm-repeater-489707-n1'
GWS = r'C:\Users\linkang\AppData\Roaming\npm\gws.cmd'
SHEET = '11BIizMMOQRWzLZi9TjvxDxn_i0949wKwMX-T9_zlYTY'

# Row format: [ID_int, key, cn, en, fr, de, po, zh, id, th, sp, ru, tr, vi, it, pl, ar, jp, kr, cns]
# cns = cn always

EVENT_START = 1011089617
ITEM_START  = 1011144320

# ── GROUP NAMES (8) ──────────────────────────────────────────────────────────
group_names = [
 ['pioneer_fest_set_site_name','工地日常','DAILY CONSTRUCTION','CHANTIER QUOTIDIEN','TÄGLICHE BAUSTELLE','OBRA DIÁRIA','工地日常','PEKERJAAN KONSTRUKSI HARIAN','การก่อสร้างประจำวัน','CONSTRUCCIÓN DIARIA','ЕЖЕДНЕВНАЯ СТРОЙКА','GÜNLÜK İNŞAAT','CÔNG TRƯỜNG HÀNG NGÀY','CANTIERE QUOTIDIANO','CODZIENNE PRACE BUDOWLANE','البناء اليومي','日常建設','일상 건설'],
 ['pioneer_fest_set_journey_name','冒险旅途','ADVENTURE JOURNEY',"VOYAGE D'AVENTURE",'ABENTEUERREISE','JORNADA DE AVENTURA','冒險旅途','PERJALANAN PETUALANGAN','การเดินทางผจญภัย','VIAJE DE AVENTURA','ПРИКЛЮЧЕНЧЕСКОЕ ПУТЕШЕСТВИЕ','MACERA YOLCULUĞU','HÀNH TRÌNH PHIÊU LƯU',"VIAGGIO D'AVVENTURA",'PODRÓŻ PRZYGODOWA','رحلة المغامرة','冒険の旅','모험 여행'],
 ['pioneer_fest_set_cowboy_name','牛仔生活','COWBOY LIFE','VIE DE COWBOY','COWBOY-LEBEN','VIDA DE COWBOY','牛仔生活','KEHIDUPAN KOBOI','ชีวิตคาวบอย','VIDA DE VAQUERO','ЖИЗНЬ КОВБОЯ','KOVBOY YAŞAMI','CUỘC SỐNG COWBOY','VITA DA COWBOY','ŻYCIE KOWBOJA','حياة الكاوبوي','カウボーイの生活','카우보이 생활'],
 ['pioneer_fest_set_monopoly_name','拓荒大富翁','PIONEER MONOPOLY','MONOPOLY PIONNIER','PIONIER-MONOPOLY','MONOPÓLIO PIONEIRO','拓荒大富翁','MONOPOLI PIONIR','โมโนโพลีผู้บุกเบิก','MONOPOLIO PIONERO','МОНОПОЛИЯ ПЕРВОПРОХОДЦА','ÖNCÜ MONOPOLY','CỜ TỶ PHÚ TIÊN PHONG','MONOPOLIO DEL PIONIERE','MONOPOLY PIONIERÓW','احتكار الرائد','パイオニアモノポリー','파이오니어 모노폴리'],
 ['pioneer_fest_set_mining_name','荒野掘金','WILDERNESS GOLD RUSH',"RUÉE VERS L'OR SAUVAGE",'WILDNIS-GOLDRAUSCH','CORRIDA DO OURO SELVAGEM','荒野掘金','DEMAM EMAS LIAR','การตื่นทองในดินแดนรกร้าง','FIEBRE DEL ORO SALVAJE','ЗОЛОТАЯ ЛИХОРАДКА В ПУСТОШИ','VAHŞİ ALTIN AKINI','CƠN SỐT VÀNG HOANG DÃ','CORSA ALL\'ORO SELVAGGIA','GORĄCZKA ZŁOTA W DZICZY','حمى الذهب البرية','荒野ゴールドラッシュ','황야의 골드러시'],
 ['pioneer_fest_set_marble_name','弹珠小游戏','MARBLE MINI-GAME','MINI-JEU DE BILLES','KUGEL-MINI-SPIEL','MINI-JOGO DE MÁRMORE','彈珠小遊戲','MINI PERMAINAN KELERENG','มินิเกมลูกแก้ว','MINIJUEGO DE CANICAS','МИНИ-ИГРА В МРАМОР','MERMERCİK MİNİ OYUNU','TRÒ CHƠI BI NHỎ','MINI GIOCO DELLE BIGLIE','MINI-GRA W KULKI','لعبة الرخام الصغيرة','マーブルミニゲーム','구슬 미니게임'],
 ['pioneer_fest_set_pusher_name','推币机','COIN PUSHER','POUSSE-PIÈCES','MÜNZSCHIEBER','EMPURRADOR DE MOEDAS','推幣機','MESIN PENDORONG KOIN','เครื่องดันเหรียญ','EMPUJADOR DE MONEDAS','МОНЕТНЫЙ ТОЛКАТЕЛЬ','MADENİ PARA İTİCİSİ','MÁY ĐẨY ĐỒNG XU','SPINGICOIN','POPYCHACZ MONET','دفع العملات','コインプッシャー','코인 푸셔'],
 ['pioneer_fest_set_hole_name','挖孔探索','HOLE EXPLORATION','EXPLORATION DES TROUS','LOCHERKUNDUNG','EXPLORAÇÃO DE BURACOS','挖孔探索','EKSPLORASI LUBANG','การสำรวจรู','EXPLORACIÓN DE HOYOS','ИССЛЕДОВАНИЕ ЯМЫ','DELİK KEŞFİ','KHÁM PHÁ HỐ','ESPLORAZIONE DI BUCHE','EKSPLORACJA DZIUR','استكشاف الحفر','穴探索','구멍 탐험'],
]

# ── CARD NAMES (72) ──────────────────────────────────────────────────────────
# Format: [key, cn, en, fr, de, po, zh, id, th, sp, ru, tr, vi, it, pl, ar, jp, kr]
card_data = [
 # G1 工地日常
 ['pioneer_fest_card_site_card_1','修筑铁路','BUILDING THE RAILWAY','CONSTRUCTION DU CHEMIN DE FER','EISENBAHNBAU','CONSTRUINDO A FERROVIA','修築鐵路','MEMBANGUN REL KERETA','สร้างทางรถไฟ','CONSTRUYENDO EL FERROCARRIL','ПРОКЛАДКА ЖЕЛЕЗНОЙ ДОРОГИ','DEMİRYOLU İNŞAATI','XÂY DỰNG ĐƯỜNG SẮT','COSTRUZIONE DELLA FERROVIA','BUDOWA KOLEI','بناء السكة الحديدية','鉄道建設','철도 건설'],
 ['pioneer_fest_card_site_card_2','工地铲沙','SHOVELING SAND','PELLETAGE DE SABLE','SAND SCHAUFELN','PALEANDO AREIA','工地鏟沙','MENYEKOP PASIR','พลั่วทราย','PALADA DE ARENA','КОПАТЬ ПЕСОК','KUM KAZMA','XÚC CÁT','PALARE SABBIA','KOPANIE PIASKU','حفر الرمال','砂をすくう','모래 삽질'],
 ['pioneer_fest_card_site_card_3','修理车轮','REPAIRING WHEELS','RÉPARATION DES ROUES','RÄDER REPARIEREN','CONSERTANDO AS RODAS','修理車輪','MEMPERBAIKI RODA','ซ่อมล้อ','REPARANDO LAS RUEDAS','РЕМОНТ КОЛЁС','TEKERLEK TAMİRİ','SỬA BÁNH XE','RIPARAZIONE DELLE RUOTE','NAPRAWA KÓŁ','إصلاح العجلات','車輪の修理','바퀴 수리'],
 ['pioneer_fest_card_site_card_4','整修粮仓','FIXING THE GRANARY','RÉNOVATION DU GRENIER','GETREIDESPEICHER REPARIEREN','CONSERTANDO O CELEIRO','整修糧倉','MEMPERBAIKI LUMBUNG','ซ่อมโกดังข้าว','ARREGLANDO EL GRANERO','РЕМОНТ АМБАРА','TAHIL DEPOSU TAMİRİ','SỬA CHỮA KHO LƯƠNG THỰC','RIPARAZIONE DEL GRANAIO','NAPRAWA SPICHLERZA','إصلاح المخزن','穀物倉の修繕','곡물창고 수리'],
 ['pioneer_fest_card_site_card_5','查看发动机','CHECKING THE ENGINE','VÉRIFICATION DU MOTEUR','MOTOR ÜBERPRÜFEN','VERIFICANDO O MOTOR','查看發動機','MEMERIKSA MESIN','ตรวจสอบเครื่องยนต์','REVISANDO EL MOTOR','ПРОВЕРКА ДВИГАТЕЛЯ','MOTORU KONTROL ETMEK','KIỂM TRA ĐỘNG CƠ','CONTROLLO DEL MOTORE','SPRAWDZANIE SILNIKA','فحص المحرك','エンジン点検','엔진 점검'],
 ['pioneer_fest_card_site_card_6','沙地飞行','DESERT FLIGHT','VOL DANS LE DÉSERT','WÜSTENFLUG','VÔO NO DESERTO','沙地飛行','PENERBANGAN DI PADANG PASIR','บินในทะเลทราย','VUELO EN EL DESIERTO','ПОЛЁТ В ПУСТЫНЕ','ÇÖLDE UÇUŞ','BAY TRÊN SA MẠC','VOLO NEL DESERTO','LOT NAD PUSTYNIĄ','الطيران في الصحراء','砂漠の飛行','사막 비행'],
 ['pioneer_fest_card_site_card_7','夜晚巡逻','NIGHT PATROL','PATROUILLE NOCTURNE','NACHTPATROUILLE','PATRULHA NOTURNA','夜晚巡逻','PATROLI MALAM','การลาดตระเวนกลางคืน','PATRULLA NOCTURNA','НОЧНОЙ ПАТРУЛЬ','GECE DEVRİYESİ','TUẦN TRA ĐÊM','PATTUGLIA NOTTURNA','NOCNY PATROL','دورية الليل','夜間パトロール','야간 순찰'],
 ['pioneer_fest_card_site_card_8','荒野讨论','WILDERNESS DISCUSSION','DISCUSSION EN PLEIN AIR','WILDNIS-DISKUSSION','DISCUSSÃO NO DESERTO','荒野討論','DISKUSI DI PADANG BELANTARA','สนทนาในดินแดนรกร้าง','DISCUSIÓN EN EL DESIERTO','ОБСУЖДЕНИЕ НА ПУСТОШИ','VAHŞI DOĞADA TARTIŞMA','THẢO LUẬN TRONG HOANG DÃ','DISCUSSIONE NEL DESERTO','DYSKUSJA NA PUSTYNI','نقاش في البرية','荒野でのディスカッション','황야 토론'],
 ['pioneer_fest_card_site_card_9','钻地行动','DRILLING OPERATION','OPÉRATION DE FORAGE','BOHRUNGSOPERATION','OPERAÇÃO DE PERFURAÇÃO','鑽地行動','OPERASI PENGEBORAN','ปฏิบัติการเจาะ','OPERACIÓN DE PERFORACIÓN','ОПЕРАЦИЯ ПО БУРЕНИЮ','DELME OPERASYONU','CHIẾN DỊCH KHOAN','OPERAZIONE DI PERFORAZIONE','OPERACJA WIERTNICZA','عملية الحفر','掘削作戦','드릴 작전'],
 # G2 冒险旅途
 ['pioneer_fest_card_journey_card_1','分析路线','ROUTE ANALYSIS','ANALYSE DE ROUTE','ROUTENANALYSE','ANÁLISE DE ROTA','分析路線','ANALISIS RUTE','วิเคราะห์เส้นทาง','ANÁLISIS DE RUTA','АНАЛИЗ МАРШРУТА','ROTA ANALİZİ','PHÂN TÍCH LỘ TRÌNH','ANALISI DEL PERCORSO','ANALIZA TRASY','تحليل الطريق','ルート分析','루트 분석'],
 ['pioneer_fest_card_journey_card_2','整装待发','GEARED UP AND READY','PRÊT À PARTIR','STARTBEREIT','PREPARADO PARA PARTIR','整裝待發','SIAP BERANGKAT','พร้อมออกเดินทาง','LISTO PARA PARTIR','ГОТОВ К ОТПРАВЛЕНИЮ','HAREKETE HAZIR','SẴN SÀNG KHỞI HÀNH','PRONTI A PARTIRE','GOTOWY DO DROGI','جاهز للانطلاق','出発準備完了','출발 준비 완료'],
 ['pioneer_fest_card_journey_card_3','分享饮水','SHARING WATER','PARTAGE DE L\'EAU','WASSER TEILEN','COMPARTILHANDO ÁGUA','分享飲水','BERBAGI AIR','แบ่งปันน้ำ','COMPARTIENDO AGUA','ДЕЛИТЬ ВОДУ','SU PAYLAŞMAK','CHIA SẺ NƯỚC UỐNG','CONDIVISIONE ACQUA','DZIELENIE SIĘ WODĄ','مشاركة الماء','水を分け合う','물 나누기'],
 ['pioneer_fest_card_journey_card_4','发现帐篷','FINDING THE TENT','DÉCOUVERTE DE LA TENTE','ZELT ENTDECKEN','DESCOBRINDO A BARRACA','發現帳篷','MENEMUKAN TENDA','พบเต็นท์','DESCUBRIENDO LA TIENDA','НАШЛИ ПАЛАТКУ','ÇADIRI BULMAK','TÌM THẤY LỀU','SCOPERTA DELLA TENDA','ODKRYCIE NAMIOTU','اكتشاف الخيمة','テントを発見','텐트 발견'],
 ['pioneer_fest_card_journey_card_5','烤火取暖','WARMING BY THE FIRE','SE RÉCHAUFFER AU FEU','AM FEUER WÄRMEN','AQUECENDO NA FOGUEIRA','烤火取暖','MENGHANGATKAN DIRI DI API','ผิงไฟให้อบอุ่น','CALENTÁNDOSE EN EL FUEGO','ГРЕТЬСЯ У КОСТРА','ATEŞTE ISINMAK','SưởI ẤM BẰNG LỬA','SCALDARSI AL FUOCO','GRZANIE SIĘ PRZY OGNIU','التدفئة بالنار','焚き火で暖まる','모닥불 쬐기'],
 ['pioneer_fest_card_journey_card_6','寻找方向','FINDING DIRECTION','TROUVER LA DIRECTION','RICHTUNG FINDEN','ENCONTRANDO A DIREÇÃO','尋找方向','MENCARI ARAH','หาทิศทาง','ENCONTRANDO LA DIRECCIÓN','ПОИСК НАПРАВЛЕНИЯ','YÖN BULMAK','TÌM HƯỚNG ĐI','TROVARE LA DIREZIONE','SZUKANIE KIERUNKU','إيجاد الاتجاه','方向を探す','방향 찾기'],
 ['pioneer_fest_card_journey_card_7','科林探路',"COLIN'S PATHFINDING",'COLIN OUVRE LA VOIE','COLINS WEGSUCHE','COLIN ABRE CAMINHO','科林探路','COLIN MENCARI JALAN','โคลินหาเส้นทาง','COLIN ABRE CAMINO','КОЛИН ПРОКЛАДЫВАЕТ ПУТЬ','COLİN YOL ARAR','COLIN TÌM ĐƯỜNG','COLIN APRE LA STRADA','COLIN SZUKA DROGI','كولن يفتح الطريق','コリンの道開き','콜린의 길 탐색'],
 ['pioneer_fest_card_journey_card_8','眺望前方','GAZING AHEAD','REGARD VERS L\'AVANT','IN DIE FERNE BLICKEN','OLHANDO PARA FRENTE','眺望前方','MEMANDANG KE DEPAN','มองไปข้างหน้า','MIRANDO HACIA ADELANTE','ВЗГЛЯД ВПЕРЁД','ÖNE BAKMAK','NHÌN VỀ PHÍA TRƯỚC','SGUARDO AL FUTURO','PATRZENIE W PRZYSZŁOŚĆ','النظر إلى الأمام','前を見据える','앞을 내다보다'],
 ['pioneer_fest_card_journey_card_9','欣赏夕阳','WATCHING THE SUNSET','ADMIRER LE COUCHER DE SOLEIL','SONNENUNTERGANG GENOSSEN','APRECIANDO O PÔR DO SOL','欣賞夕陽','MENIKMATI MATAHARI TERBENAM','ชมพระอาทิตย์ตกดิน','ADMIRANDO EL ATARDECER','ЛЮБОВАТЬСЯ ЗАКАТОМ','GÜNBATIMINI IZLEMEK','NGẮM HOÀNG HÔN','AMMIRARE IL TRAMONTO','PODZIWIANIE ZACHODU SŁOŃCA','مشاهدة غروب الشمس','夕日を眺める','석양 감상'],
 # G3 牛仔生活
 ['pioneer_fest_card_cowboy_card_1','荒野警长','WILDERNESS SHERIFF','SHÉRIF DU DÉSERT','WILDNIS-SHERIFF','XERIFE DO DESERTO','荒野警長','SHERIFF PADANG LIAR','นายอำเภอในดินแดนรกร้าง','SHERIFF DEL DESIERTO','ШЕРИФ ПУСТОШИ','VAHŞI DOĞA ŞERİFİ','CẢNH SÁT TRƯỞNG HOANG DÃ','SCERIFFO DEL DESERTO','SZERYF PUSTYNI','شريف البرية','荒野の保安官','황야의 보안관'],
 ['pioneer_fest_card_cowboy_card_2','保养火车','MAINTAINING THE TRAIN','ENTRETIEN DU TRAIN','ZUG WARTEN','MANUTENÇÃO DO TREM','保養火車','PERAWATAN KERETA','บำรุงรักษารถไฟ','MANTENIMIENTO DEL TREN','ОБСЛУЖИВАНИЕ ПОЕЗДА','TREN BAKIMI','BẢO TRÌ TÀU HỎA','MANUTENZIONE DEL TRENO','KONSERWACJA POCIĄGU','صيانة القطار','列車の整備','기차 정비'],
 ['pioneer_fest_card_cowboy_card_3','自由滑沙','FREE SAND SLIDING','GLISSADE LIBRE SUR LE SABLE','FREIES SANDSURFEN','DESLIZANDO LIVREMENTE NA AREIA','自由滑沙','MELUNCUR BEBAS DI PASIR','เล่นทรายอย่างอิสระ','DESLIZANDO LIBRE EN LA ARENA','СВОБОДНОЕ СКОЛЬЖЕНИЕ ПО ПЕСКУ','ÖZGÜR KUM KAYMASI','TRƯỢT CÁT TỰ DO','SCIVOLATA LIBERA SULLA SABBIA','SWOBODNE ŚLIZGANIE PO PIASKU','الانزلاق الحر على الرمال','自由砂滑り','자유 모래 슬라이딩'],
 ['pioneer_fest_card_cowboy_card_4','补充饮水','REPLENISHING WATER','RECHARGER EN EAU','WASSER AUFFÜLLEN','REABASTECENDO ÁGUA','補充飲水','MENGISI ULANG AIR','เติมน้ำดื่ม','REABASTECIENDO AGUA','ПОПОЛНЕНИЕ ЗАПАСОВ ВОДЫ','SU İKMALİ','BỔ SUNG NƯỚC UỐNG','RIFORNIMENTO IDRICO','UZUPEŁNIANIE WODY','تجديد المياه','水の補給','물 보충'],
 ['pioneer_fest_card_cowboy_card_5','眺望列车','WATCHING THE TRAIN','REGARDER LE TRAIN','ZUG BEOBACHTEN','OBSERVANDO O TREM','眺望列車','MEMANDANG KERETA','มองรถไฟ','OBSERVANDO EL TREN','НАБЛЮДАТЬ ЗА ПОЕЗДОМ','TRENI IZLEMEK','NGẮM TÀU HỎA','GUARDARE IL TRENO','OGLĄDANIE POCIĄGU','مراقبة القطار','列車を眺める','기차 구경'],
 ['pioneer_fest_card_cowboy_card_6','西部牛仔','WESTERN COWBOY','COWBOY DE L\'OUEST','WESTLICHER COWBOY','COWBOY DO OESTE','西部牛仔','COWBOY BARAT','คาวบอยตะวันตก','VAQUERO DEL OESTE','ЗАПАДНЫЙ КОВБОЙ','BATI KOVBOYU','CAO BỒI PHƯƠNG TÂY','COWBOY DEL WEST','ZACHODNI KOWBOJ','كاوبوي الغرب','ウエスタンカウボーイ','서부 카우보이'],
 ['pioneer_fest_card_cowboy_card_7','篝火之夜','BONFIRE NIGHT','NUIT AU FEU DE CAMP','LAGERFEUER-NACHT','NOITE DE FOGUEIRA','篝火之夜','MALAM UNGGUN API','คืนกองไฟ','NOCHE DE FOGATA','НОЧЬ У КОСТРА','KAMP ATEŞİ GECESİ','ĐÊM LỬA TRẠI','NOTTE DEL FALÒ','NOC PRZY OGNISKU','ليلة نار المخيم','キャンプファイヤーの夜','모닥불의 밤'],
 ['pioneer_fest_card_cowboy_card_8','准备起飞','READY FOR TAKEOFF','PRÊT AU DÉCOLLAGE','BEREIT ZUM ABFLUG','PRONTO PARA DECOLAR','準備起飛','SIAP TERBANG','พร้อมบินขึ้น','LISTO PARA DESPEGAR','ГОТОВ К ВЗЛЁТУ','KALKIŞA HAZIR','SẴN SÀNG CẤT CÁNH','PRONTO AL DECOLLO','GOTOWY DO STARTU','استعداد للإقلاع','離陸準備完了','이륙 준비'],
 ['pioneer_fest_card_cowboy_card_9','沙地狂飙','DESERT SPRINT','SPRINT DANS LE DÉSERT','WÜSTEN-SPRINT','CORRIDA NO DESERTO','沙地狂飆','SPRINT DI PADANG PASIR','วิ่งเร็วในทะเลทราย','SPRINT EN EL DESIERTO','СПРИНТ В ПУСТЫНЕ','ÇÖLDEYARIŞ','ĐUA XE SA MẠC','SPRINT NEL DESERTO','SPRINT NA PUSTYNI','سباق الصحراء','砂漠のスプリント','사막 스프린트'],
 # G4 拓荒大富翁
 ['pioneer_fest_card_monopoly_card_1','解锁雷达','UNLOCKING THE RADAR','DÉBLOCAGE DU RADAR','RADAR FREISCHALTEN','DESBLOQUEANDO O RADAR','解鎖雷達','MEMBUKA KUNCI RADAR','ปลดล็อกเรดาร์','DESBLOQUEANDO EL RADAR','РАЗБЛОКИРОВКА РАДАРА','RADARI KİLİDİ AÇMAK','MỞ KHÓA RADAR','SBLOCCARE IL RADAR','ODBLOKOWANIE RADARU','إلغاء قفل الرادار','レーダー解除','레이더 잠금 해제'],
 ['pioneer_fest_card_monopoly_card_2','收获丰盛','BOUNTIFUL HARVEST','RÉCOLTE ABONDANTE','REICHE ERNTE','COLHEITA ABUNDANTE','收穫豐盛','PANEN BERLIMPAH','เก็บเกี่ยวอุดมสมบูรณ์','COSECHA ABUNDANTE','БОГАТЫЙ УРОЖАЙ','BOL HASAT','VỤ MÙA BỘI THU','RACCOLTO ABBONDANTE','OBFITE ZBIORY','حصاد وفير','豊かな収穫','풍성한 수확'],
 ['pioneer_fest_card_monopoly_card_3','神秘卡片','MYSTERY CARD','CARTE MYSTÈRE','MYSTERIÖSE KARTE','CARTA MISTERIOSA','神秘卡片','KARTU MISTERIUS','การ์ดลึกลับ','CARTA MISTERIOSA','ТАИНСТВЕННАЯ КАРТА','GIZEMLI KART','LÁ BÀI BÍ ẨN','CARTA MISTERIOSA','TAJEMNICZA KARTA','بطاقة غامضة','ミステリーカード','미스터리 카드'],
 ['pioneer_fest_card_monopoly_card_4','打开奖赏','OPENING THE REWARD','OUVRIR LA RÉCOMPENSE','BELOHNUNG ÖFFNEN','ABRINDO A RECOMPENSA','打開獎賞','MEMBUKA HADIAH','เปิดรางวัล','ABRIENDO LA RECOMPENSA','ОТКРЫТЬ НАГРАДУ','ÖDÜLÜ AÇMAK','MỞ PHẦN THƯỞNG','APRIRE LA RICOMPENSA','OTWIERANIE NAGRODY','فتح المكافأة','報酬を開ける','보상 열기'],
 ['pioneer_fest_card_monopoly_card_5','期待好运','HOPING FOR LUCK','ESPÉRER LA CHANCE','AUF GLÜCK HOFFEN','ESPERANDO BOA SORTE','期待好運','BERHARAP KEBERUNTUNGAN','หวังโชคดี','ESPERANDO BUENA SUERTE','НАДЕЯТЬСЯ НА УДАЧУ','ŞANS UMMAK','HI VỌNG MAY MẮN','SPERARE IN FORTUNA','MIEĆ NADZIEJĘ NA SZCZĘŚCIE','الأمل في الحظ','幸運を期待する','행운을 바라다'],
 ['pioneer_fest_card_monopoly_card_6','大步向前','STRIDING FORWARD','AVANCER À GRANDS PAS','GROSSE SCHRITTE VORWÄRTS','AVANÇANDO A PASSOS LARGOS','大步向前','MELANGKAH MAJU','ก้าวเดินไปข้างหน้า','AVANZANDO A GRANDES PASOS','ШАГАТЬ ВПЕРЁД','BÜYÜK ADIMLARLA İLERLEMEK','TIẾN BƯỚC VỀ PHÍA TRƯỚC','AVANZARE A GRANDI PASSI','WIELKIE KROKI NAPRZÓD','المضي قدمًا','大きな一歩で前進','큰 걸음으로 전진'],
 ['pioneer_fest_card_monopoly_card_7','思考战术','TACTICAL THINKING','RÉFLEXION TACTIQUE','TAKTISCHES DENKEN','PENSAMENTO TÁTICO','思考戰術','PEMIKIRAN TAKTIS','คิดเชิงยุทธวิธี','PENSAMIENTO TÁCTICO','ТАКТИЧЕСКОЕ МЫШЛЕНИЕ','TAKTİK DÜŞÜNMEK','TƯ DUY CHIẾN THUẬT','PENSIERO TATTICO','MYŚLENIE TAKTYCZNE','التفكير التكتيكي','戦術的思考','전술적 사고'],
 ['pioneer_fest_card_monopoly_card_8','愁眉苦脸','DOWNCAST FACE','VISAGE RENFROGNÉ','BETRÜBTES GESICHT','ROSTO ABATIDO','愁眉苦臉','WAJAH MURUNG','หน้าตาหม่นหมอง','CARA TRISTE','УНЫЛОЕ ЛИЦО','ASIK YÜZ','KHUÔN MẶT ỦE OẢI','VISO ABBATTUTO','SMUTNA TWARZ','وجه حزين','しかめっ面','우울한 표정'],
 ['pioneer_fest_card_monopoly_card_9','夺得宝石','CLAIMING THE GEM','REMPORTER LE JOYAU','DAS JUWEL ERRINGEN','CONQUISTANDO A GEMA','奪得寶石','MEREBUT PERMATA','คว้าอัญมณี','GANANDO LA GEMA','ЗАВОЕВАТЬ ДРАГОЦЕННЫЙ КАМЕНЬ','MÜCEVHERİ KAZANMAK','GIÀNH LẤY ĐÁ QUÝ','AGGIUDICARSI IL GIOIELLO','ZDOBYCIE KLEJNOTU','الفوز بالجوهرة','宝石を手に入れる','보석 획득'],
 # G5 荒野掘金
 ['pioneer_fest_card_mining_card_1','施工现场','CONSTRUCTION SITE','CHANTIER DE CONSTRUCTION','BAUSTELLE','CANTEIRO DE OBRAS','施工現場','LOKASI KONSTRUKSI','สถานที่ก่อสร้าง','SITIO DE CONSTRUCCIÓN','СТРОЙПЛОЩАДКА','İNŞAAT SAHASI','CÔNG TRƯỜNG XÂY DỰNG','CANTIERE DI COSTRUZIONE','PLAC BUDOWY','موقع البناء','建設現場','건설 현장'],
 ['pioneer_fest_card_mining_card_2','宝矿出土','TREASURE UNEARTHED','TRÉSOR DÉTERRÉ','SCHATZ AUSGEGRABEN','TESOURO DESENTERRADO','寶礦出土','HARTA KARUN TERGALI','ขุดพบสมบัติ','TESORO DESENTERRADO','РАСКОПАННОЕ СОКРОВИЩЕ','HAZİNE KAZILDI','ĐÀO ĐƯỢC KHO BÁU','TESORO DISSOTTERRATO','ODKRYTY SKARB','كنز مستخرج','宝を発掘','보물 발굴'],
 ['pioneer_fest_card_mining_card_3','埋头苦干','WORKING HARD','TRAVAIL ACHARNÉ','HART ARBEITEN','TRABALHANDO DURO','埋頭苦幹','BEKERJA KERAS','ทำงานหนัก','TRABAJAR DURO','УСЕРДНО РАБОТАТЬ','ÇALIŞKAN OLMAK','LÀM VIỆC CHĂM CHỈ','LAVORARE DURO','CIĘŻKA PRACA','العمل بجد','猛烈に働く','열심히 일하다'],
 ['pioneer_fest_card_mining_card_4','发现金块','GOLD NUGGET FOUND','PÉPITE D\'OR TROUVÉE','GOLDNUGGET GEFUNDEN','PEPITA DE OURO ENCONTRADA','發現金塊','MENEMUKAN BONGKAHAN EMAS','พบก้อนทอง','PEPITA DE ORO ENCONTRADA','НАЙДЕН САМОРОДОК','ALTIN KÜLÇE BULUNDU','TÌM THẤY THỎI VÀNG','PEPITA D\'ORO TROVATA','ZNALEZIONO BRYŁKĘ ZŁOTA','العثور على كتلة ذهب','金塊発見','금덩이 발견'],
 ['pioneer_fest_card_mining_card_5','齐头并进','ADVANCING TOGETHER','AVANCER ENSEMBLE','GEMEINSAM VORANSCHREITEN','AVANÇANDO JUNTOS','齊頭並進','MAJU BERSAMA','ก้าวไปพร้อมกัน','AVANZANDO JUNTOS','ИДТИ ВРОВЕНЬ','BIRLIKTE İLERLEMEK','CÙNG TIẾN LÊN','AVANZARE INSIEME','WSPÓLNE KROKI','التقدم معًا','共に前進','함께 전진'],
 ['pioneer_fest_card_mining_card_6','电光火石','ELECTRIC SPARK','ÉCLAIR ÉLECTRIQUE','ELEKTRISCHER FUNKE','FAÍSCA ELÉTRICA','電光火石','KILAT LISTRIK','ประกายไฟฟ้า','CHISPA ELÉCTRICA','ЭЛЕКТРИЧЕСКАЯ ИСКРА','ELEKTRİK KIVI LCIĞI','TIA CHỚP ĐIỆN','SCINTILLA ELETTRICA','ELEKTRYCZNA ISKRA','شرارة كهربائية','電光石火','전기 불꽃'],
 ['pioneer_fest_card_mining_card_7','力大无穷','MIGHTY STRENGTH','FORCE IMMENSE','UNENDLICHE KRAFT','FORÇA IMENSURÁVEL','力大無窮','KEKUATAN LUAR BIASA','พลังอันยิ่งใหญ่','FUERZA INMENSA','НЕВЕРОЯТНАЯ СИЛА','SONSUZ GÜÇ','SỨC MẠNH VÔ TẬN','FORZA IMMENSA','NIEZMIERZONA SIŁA','قوة هائلة','無限の力','무한한 힘'],
 ['pioneer_fest_card_mining_card_8','盆满钵满','BASKETS OVERFLOWING','PANIERS DÉBORDANTS','KÖRBE ÜBERVOLL','CESTAS TRANSBORDANDO','盆滿缽滿','KERANJANG PENUH','ตะกร้าเต็มล้น','CESTAS REBOSANTES','КОРЗИНЫ ПОЛНЫЕ','DOLU SEPETLER','ĐẦY ẮP TỚI BỜ','CESTE TRABOCCANTI','KOSZE PRZEPEŁNIONE','سلال مليئة','溢れかえるカゴ','넘치는 바구니'],
 ['pioneer_fest_card_mining_card_9','淘洗金块','PANNING FOR GOLD','CHERCHER DE L\'OR','GOLD WASCHEN','PENEIRANDO OURO','淘洗金塊','MENDULANG EMAS','ร่อนทอง','BATEANDO ORO','ПРОМЫВАТЬ ЗОЛОТО','ALTIN YIKAMAK','ĐÃI VÀNG','CERCANDO L\'ORO','PŁUKANIE ZŁOTA','تنقية كتل الذهب','砂金採り','사금 채취'],
 # G6 弹珠小游戏
 ['pioneer_fest_card_marble_card_1','荒野弹珠台','WILDERNESS PINBALL TABLE','TABLE DE FLIPPER SAUVAGE','WILDNIS-FLIPPERTISCH','MESA DE FLIPERAMA NO DESERTO','荒野彈珠台','MEJA PINBALL LIAR','โต๊ะพินบอลในดินแดนรกร้าง','MESA DE PINBALL EN EL DESIERTO','ДИКИЙ ПИНБАЛЬНЫЙ СТОЛ','VAHŞİ MASA OYUNU','BÀN ĐÁ BI HOANG DÃ','FLIPPER SELVAGGIO','DZIKI STÓŁ DO PINBALLA','طاولة النيلة البرية','荒野のピンボール台','황야 핀볼 테이블'],
 ['pioneer_fest_card_marble_card_2','弹射出发','LAUNCHING OFF','LANCEMENT','ABSCHUSS','LANÇANDO','彈射出發','MELUNCUR','ยิงออกตัว','LANZAMIENTO','ЗАПУСТИТЬ','ATEŞLE','PHÓNG ĐI','LANCIO','WYSTRZELENIE','الانطلاق','発射スタート','발사 출발'],
 ['pioneer_fest_card_marble_card_3','连珠妙弹','CHAIN TRICK SHOT','TIR ENCHAÎNÉ PARFAIT','KETTENKUNSTSCHUSS','ARREMESSO EM CADEIA','連珠妙彈','TEMBAKAN BERANTAI','ยิงลูกแก้วติดต่อกัน','TIRO ENCADENADO PERFECTO','ЦЕПНОЙ МЕТКИЙ ВЫСТРЕЛ','ZİNCİR NİŞAN ATIŞ','ĐẠN LIÊN HOÀN','TIRO CONCATENATO','SERIA TRAFIEŃ','رمية متسلسلة بارعة','連続妙技ショット','연속 기술 샷'],
 ['pioneer_fest_card_marble_card_4','完美入洞','PERFECT HOLE-IN-ONE','TROU EN UN PARFAIT','PERFEKTER LOCH-IN-EINEM','BURACO EM UM PERFEITO','完美入洞','HOLE-IN-ONE SEMPURNA','โฮลอินวันสมบูรณ์แบบ','HOYO EN UNO PERFECTO','ИДЕАЛЬНЫЙ УДАР','MÜKEMMEL DELIK','HOÀN HẢO TRONG LỖ','BUCO IN UNO PERFETTO','IDEALNE TRAFIENIE W DZIURĘ','حفرة في واحدة مثالية','パーフェクトホールインワン','완벽한 홀인원'],
 ['pioneer_fest_card_marble_card_5','翻板救球','FLIPPER SAVE','SAUVETAGE PAR FLIPPER','FLIPPER-RETTUNG','SALVA DA FLIPPER','翻板救球','PENYELAMATAN FLIPPER','พลิกแผ่นช่วยลูก','SALVADA DE FLIPPER','СПАСЕНИЕ ФЛИППЕРОМ','FLIPPER KURTARMA','CỨU BÓNG BẰNG CÁNH GẬT','SALVATAGGIO DAL FLIPPER','URATOWANIE PRZEZ ZDERZAK','إنقاذ زعنفة','フリッパーで救う','플리퍼 세이브'],
 ['pioneer_fest_card_marble_card_6','加注下赌','RAISING THE STAKES','RELANCER LES ENCHÈRES','EINSATZ ERHÖHEN','AUMENTANDO AS APOSTAS','加注下賭','MENAIKKAN TARUHAN','เพิ่มเดิมพัน','SUBIR LAS APUESTAS','ПОВЫСИТЬ СТАВКИ','BAHSİ YÜKSELTİT','TĂNG CƯỢC','ALZARE LA POSTA','PODNOSZENIE STAWKI','رفع الرهان','賭け金を上げる','판돈 올리기'],
 ['pioneer_fest_card_marble_card_7','修台调试','TABLE TUNING','RÉGLAGE DE TABLE','TISCHJUSTIERUNG','AJUSTE DA MESA','修台調試','PENYETELAN MEJA','ปรับโต๊ะ','AJUSTE DE MESA','НАСТРОЙКА СТОЛА','MASA AYARI','ĐIỀU CHỈNH BÀN','REGOLAZIONE DEL TAVOLO','REGULACJA STOŁU','ضبط الطاولة','台の調整','테이블 조정'],
 ['pioneer_fest_card_marble_card_8','酒馆对决','TAVERN SHOWDOWN','DUEL AU SALOON','TAVERNE-DUELL','CONFRONTO NA TABERNA','酒館對決','DUEL DI KEDAI','การดวลในผับ','DUELO EN LA TABERNA','ДУЭЛЬ В ТАВЕРНЕ','MEYHANE DÜELLOSU','ĐẤU TRONG QUÁN RượU','DUELLO ALLA TAVERNA','POJEDYNEK W TAWERNIE','مبارزة في الحانة','酒場の決闘','주점 대결'],
 ['pioneer_fest_card_marble_card_9','满载金矿','LOADED WITH GOLD','CHARGÉ DE MINERAI D\'OR','MIT GOLD BELADEN','CARREGADO DE OURO','滿載金礦','PENUH EMAS','บรรทุกทองเต็ม','CARGADO DE ORO','НАГРУЖЕН ЗОЛОТОМ','ALTINLA YÜKLÜ','ĐẦY ẮP VÀNG','CARICO DI ORO','ZAŁADOWANY ZŁOTEM','محمل بالذهب','金鉱を積んで','금광 가득'],
 # G7 推币机
 ['pioneer_fest_card_pusher_card_1','投币开局','INSERT COIN TO START','INSÉRER UNE PIÈCE POUR COMMENCER','MÜNZE EINWERFEN','INSERIR MOEDA PARA COMEÇAR','投幣開局','MASUKKAN KOIN UNTUK MULAI','หยอดเหรียญเพื่อเริ่ม','INSERTAR MONEDA PARA COMENZAR','ВСТАВЬТЕ МОНЕТУ ДЛЯ НАЧАЛА','BAŞLAMAK İÇİN MADENİ PARA AT','BỎ ĐỒNG XU ĐỂ BẮT ĐẦU','INSERISCI MONETA PER INIZIARE','WRZUĆ MONETĘ ABY ZACZĄĆ','ادفع عملة للبدء','コインを入れてスタート','동전 투입 시작'],
 ['pioneer_fest_card_pusher_card_2','矿洞怪兽','MINE MONSTER','MONSTRE DE LA MINE','MINENMONSTER','MONSTRO DA MINA','礦洞怪獸','MONSTER TAMBANG','สัตว์ประหลาดในเหมือง','MONSTRUO DE LA MINA','МОНСТР ШАХТЫ','MADEN CANAVARı','QUÁI VẬT HẦM MỎ','MOSTRO DELLA MINIERA','POTWÓR Z KOPALNI','وحش المنجم','鉱山のモンスター','광산 몬스터'],
 ['pioneer_fest_card_pusher_card_3','金币如雨','RAIN OF GOLD COINS','PLUIE DE PIÈCES D\'OR','GOLDREGEN','CHUVA DE MOEDAS DE OURO','金幣如雨','HUJAN KOIN EMAS','ฝนเหรียญทอง','LLUVIA DE MONEDAS DE ORO','ДОЖДЬ ЗОЛОТЫХ МОНЕТ','ALTIN YAĞMURU','MƯA ĐỒNG VÀNG','PIOGGIA DI MONETE D\'ORO','DESZCZ ZŁOTYCH MONET','مطر من العملات الذهبية','金貨の雨','금화 비'],
 ['pioneer_fest_card_pusher_card_4','硬币叠塔','COIN TOWER','TOUR DE PIÈCES','MÜNZTURM','TORRE DE MOEDAS','硬幣疊塔','MENARA KOIN','หอเหรียญ','TORRE DE MONEDAS','БАШНЯ ИЗ МОНЕТ','PARA KULESİ','THÁP ĐỒNG XU','TORRE DI MONETE','WIEŻA Z MONET','برج من العملات','コインの塔','동전 탑'],
 ['pioneer_fest_card_pusher_card_5','精准铲币','PRECISE COIN SWEEP','BALAYAGE DE PIÈCES PRÉCIS','PRÄZISES MÜNZ-KEHREN','VARREDURA PRECISA DE MOEDAS','精準鏟幣','SAPU KOIN TEPAT','กวาดเหรียญอย่างแม่นยำ','BARRIDO PRECISO DE MONEDAS','ТОЧНАЯ СГРЕБАНИЕ МОНЕТ','KESİN PARA SÜPÜRME','QUÉT ĐỒNG XU CHÍNH XÁC','RACCOLTA MONETE PRECISA','PRECYZYJNE ZBIERANIE MONET','كنس العملات بدقة','精密なコイン掃き','정밀 코인 쓸기'],
 ['pioneer_fest_card_pusher_card_6','悬崖时刻',"CLIFF'S EDGE MOMENT",'MOMENT AU BORD DU PRÉCIPICE','AM RAND DES ABGRUNDS','MOMENTO À BEIRA DO PENHASCO','懸崖時刻','MOMEN DI TEPI JURANG','ช่วงเวลาริมหน้าผา','MOMENTO AL BORDE DEL PRECIPICIO','МОМЕНТ НА КРАЮ ПРОПАСТИ','UÇURUM ANI','KHOẢNH KHẮC BÊN VÁCH ĐÁ','MOMENTO SUL PRECIPIZIO','MOMENT NA KRAWĘDZI','لحظة على حافة الهاوية','崖っぷちの瞬間','절벽의 순간'],
 ['pioneer_fest_card_pusher_card_7','驯服怪兽','TAMING THE MONSTER','APPRIVOISER LE MONSTRE','DAS MONSTER ZÄHMEN','DOMANDO O MONSTRO','馴服怪獸','MENJINAKKAN MONSTER','ฝึกสัตว์ประหลาด','DOMANDO AL MONSTRUO','ПРИРУЧИТЬ МОНСТРА','CANAVARLA MÜCADELE','THUẦN PHỤC QUÁI VẬT','ADDOMESTICARE IL MOSTRO','OSWAJANIE POTWORA','ترويض الوحش','モンスターを手なずける','몬스터 길들이기'],
 ['pioneer_fest_card_pusher_card_8','连锁推落','CHAIN PUSH-OFF','POUSSÉE EN CHAÎNE','KETTENSTOSS','EMPURRÃO EM CADEIA','連鎖推落','DORONGAN BERANTAI','ผลักล้มเป็นลูกโซ่','EMPUJE EN CADENA','ЦЕПНОЕ ВЫТАЛКИВАНИЕ','ZİNCİR İTME','ĐẨY DÂY CHUYỀN','SPINTA A CATENA','ŁAŃCUCHOWE POPCHNIĘCIE','دفع سلسلي','連鎖プッシュ','연쇄 밀어내기'],
 ['pioneer_fest_card_pusher_card_9','金矿大逃亡','GOLD MINE ESCAPE','ÉVASION DE LA MINE D\'OR','FLUCHT AUS DER GOLDMINE','FUGA DA MINA DE OURO','金礦大逃亡','KABUR DARI TAMBANG EMAS','หนีจากเหมืองทอง','ESCAPE DE LA MINA DE ORO','ПОБЕГ ИЗ ЗОЛОТОЙ ШАХТЫ','ALTIN MADEN KAÇIŞI','ĐẠI THOÁT KHỎI MỎ VÀNG','FUGA DALLA MINIERA D\'ORO','WIELKA UCIECZKA Z KOPALNI','هروب كبير من منجم الذهب','金鉱大脱走','금광 대탈출'],
 # G8 挖孔探索
 ['pioneer_fest_card_hole_card_1','能量钻头','POWER DRILL','FOREUSE PUISSANTE','KRAFTBOHRER','FURADEIRA POTENTE','能量鑽頭','BOR BERTENAGA','สว่านพลังงาน','TALADRO POTENTE','СИЛОВОЙ БУРИЛЬНЫЙ','GÜÇ MATKESİ','MŨI KHOAN ĐIỆN','TRAPANO POTENTE','WIERTALNIK ELEKTRYCZNY','مثقاب الطاقة','パワードリル','전동 드릴'],
 ['pioneer_fest_card_hole_card_2','启动探测','ACTIVATING DETECTION','ACTIVATION DE LA DÉTECTION','DETEKTION AKTIVIEREN','ATIVANDO DETECÇÃO','啟動探測','MENGAKTIFKAN DETEKSI','เปิดใช้งานการตรวจจับ','ACTIVANDO DETECCIÓN','ЗАПУСК ОБНАРУЖЕНИЯ','TESPİT AKTİFLEŞTİRME','KÍCH HOẠT PHÁT HIỆN','ATTIVAZIONE DEL RILEVAMENTO','AKTYWOWANIE WYKRYWANIA','تفعيل الكشف','探知システム起動','탐지 활성화'],
 ['pioneer_fest_card_hole_card_3','电磁宝箱','ELECTROMAGNETIC CHEST','COFFRE ÉLECTROMAGNÉTIQUE','ELEKTROMAGNETISCHE TRUHE','BAÚL ELETROMAGNÉTICO','電磁寶箱','PETI ELEKTROMAGNETIK','หีบสมบัติแม่เหล็กไฟฟ้า','COFRE ELECTROMAGNÉTICO','ЭЛЕКТРОМАГНИТНЫЙ СУНДУК','ELEKTROMANYETİK SANDIK','HÒM BÁU ĐIỆN TỪ','FORZIERE ELETTROMAGNETICO','SKRZYNIA ELEKTROMAGNETYCZNA','صندوق كنز كهرومغناطيسي','電磁宝箱','전자기 보물상자'],
 ['pioneer_fest_card_hole_card_4','补给运输','SUPPLY TRANSPORT','TRANSPORT DE RAVITAILLEMENT','VERSORGUNGSTRANSPORT','TRANSPORTE DE SUPRIMENTOS','補給運輸','TRANSPORTASI LOGISTIK','การขนส่งเสบียง','TRANSPORTE DE SUMINISTROS','ТРАНСПОРТИРОВКА СНАРЯЖЕНИЯ','İKMAL TAŞIMACILIĞI','VẬN CHUYỂN TIẾP TẾ','TRASPORTO DI RIFORNIMENTI','TRANSPORT ZAOPATRZENIA','نقل الإمدادات','補給輸送','보급 수송'],
 ['pioneer_fest_card_hole_card_5','矿石鉴定','ORE IDENTIFICATION','IDENTIFICATION DU MINERAI','ERZKUNDE','IDENTIFICAÇÃO DE MINÉRIO','礦石鑑定','IDENTIFIKASI BIJIH','การระบุแร่','IDENTIFICACIÓN DE MINERAL','ИДЕНТИФИКАЦИЯ РУДЫ','CEVHER TANIMLAMASI','NHẬN DIỆN QUẶNG','IDENTIFICAZIONE DEL MINERALE','IDENTYFIKACJA RUDY','تحديد الخام','鉱石鑑定','광석 감정'],
 ['pioneer_fest_card_hole_card_6','信号灯','SIGNAL LIGHT','FEU DE SIGNALISATION','SIGNALLAMPE','LUZ DE SINAL','信號燈','LAMPU SINYAL','ไฟสัญญาณ','LUZ DE SEÑAL','СИГНАЛЬНЫЙ ОГОНЬ','SİNYAL IŞIĞI','ĐÈN TÍN HIỆU','LUCE DI SEGNALE','ŚWIATŁO SYGNAŁOWE','ضوء الإشارة','シグナルライト','신호등'],
 ['pioneer_fest_card_hole_card_7','工具清点','TOOL INVENTORY','INVENTAIRE DES OUTILS','WERKZEUGBESTAND','INVENTÁRIO DE FERRAMENTAS','工具清點','INVENTARIS ALAT','ตรวจนับเครื่องมือ','INVENTARIO DE HERRAMIENTAS','ИНВЕНТАРИЗАЦИЯ ИНСТРУМЕНТОВ','ALET ENVANTERİ','KIỂM KÊ DỤNG CỤ','INVENTARIO DEGLI STRUMENTI','INWENTARZ NARZĘDZI','جرد الأدوات','ツール棚卸し','도구 재고조사'],
 ['pioneer_fest_card_hole_card_8','弹簧拉锯','SPRING SAW','SCIE À RESSORT','FEDERSÄGE','SERRA DE MOLA','彈簧拉鋸','GERGAJI PEGAS','เลื่อยสปริง','SIERRA DE MUELLE','ПРУЖИННАЯ ПИЛА','YAYLI TESTERE','CƯA LÒ XO','SEGA A MOLLA','PIŁA SPRĘŻYNOWA','منشار زنبركي','スプリングソー','스프링 톱'],
 ['pioneer_fest_card_hole_card_9','终极发现','ULTIMATE DISCOVERY','DÉCOUVERTE ULTIME','ULTIMATIVE ENTDECKUNG','DESCOBERTA FINAL','終極發現','PENEMUAN AKHIR','การค้นพบขั้นสุดยอด','DESCUBRIMIENTO FINAL','ВЕЛИЧАЙШЕЕ ОТКРЫТИЕ','MUHTEŞEM KEŞİF','KHÁM PHÁ CUỐI CÙNG','SCOPERTA FINALE','OSTATECZNE ODKRYCIE','الاكتشاف النهائي','究極の発見','궁극의 발견'],
]

# ── ITEM PACK NAMES + DESCS (22) ──────────────────────────────────────────────
item_data = [
 ['pioneer_fest_pack_dig_hole_name','拓荒节-挖孔主题卡包','Pioneer Day - Dig Hole Theme Card Pack','Pioneer Day - Pack Thématique Exploration de Trous','Pioneer Day - Thematische Locherkundungs-Kartenpackung','Pioneer Day - Pacote Temático de Exploração de Buracos','拓荒節-挖孔主題卡包','Pioneer Day - Paket Kartu Tema Eksplorasi Lubang','Pioneer Day - ชุดการ์ดสำรวจรู','Pioneer Day - Pack Temático de Exploración de Hoyos','Pioneer Day - Тематический набор «Исследование ям»','Pioneer Day - Delik Keşfi Temalı Kart Paketi','Pioneer Day - Gói Bài Khám Phá Hố','Pioneer Day - Pacchetto Tema Esplorazione Buche','Pioneer Day - Tematyczna Paczka Eksploracji Dziur','يوم الرائد - حزمة استكشاف الحفر الموضوعية','パイオニアデー - 穴探索テーマカードパック','파이오니어 데이 - 구멍 탐험 테마 카드팩'],
 ['pioneer_fest_pack_dig_hole_desc','打开即可获得2张3星及以上的「挖孔探索」游戏卡片。','Open to receive 2 "Hole Exploration" game cards of 3 stars or above.','Ouvrez pour recevoir 2 cartes de jeu "Exploration des Trous" de 3 étoiles ou plus.','Öffnen, um 2 "Locherkundung"-Spielkarten mit 3 Sternen oder mehr zu erhalten.','Abra para receber 2 cartas de jogo "Exploração de Buracos" de 3 estrelas ou acima.','打開即可獲得2張3星及以上的「挖孔探索」遊戲卡片。','Buka untuk mendapatkan 2 kartu permainan "Eksplorasi Lubang" bintang 3 atau lebih.','เปิดเพื่อรับการ์ดเกม "สำรวจรู" 2 ใบ 3 ดาวขึ้นไป','Abre para recibir 2 cartas del juego "Exploración de Hoyos" de 3 estrellas o más.','Откройте, чтобы получить 2 игровые карточки «Исследование ям» 3 звезды и выше.','Açarak "Delik Keşfi" oyun kartlarından 3 yıldız veya daha fazla 2 adet alın.','Mở để nhận 2 thẻ bài trò chơi "Khám Phá Hố" từ 3 sao trở lên.','Apri per ricevere 2 carte di gioco "Esplorazione Buche" di 3 stelle o superiori.','Otwórz, aby otrzymać 2 karty "Eksploracja Dziur" o 3 gwiazdkach lub więcej.','افتح للحصول على بطاقتي لعبة "استكشاف الحفر" من 3 نجوم أو أكثر.','開けると「穴探索」ゲームカードが3★以上2枚もらえます。','열면 "구멍 탐험" 게임 카드 3성 이상 2장을 받을 수 있습니다.'],
 ['pioneer_fest_pack_mining_name','拓荒节-挖矿主题卡包','Pioneer Day - Mining Theme Card Pack','Pioneer Day - Pack Thématique Ruée vers l\'Or','Pioneer Day - Goldgräber-Themenkartenpackung','Pioneer Day - Pacote Temático de Mineração','拓荒節-挖礦主題卡包','Pioneer Day - Paket Kartu Tema Pertambangan','Pioneer Day - ชุดการ์ดธีมทำเหมืองแร่','Pioneer Day - Pack Temático de Minería','Pioneer Day - Тематический набор «Добыча золота»','Pioneer Day - Madencilik Temalı Kart Paketi','Pioneer Day - Gói Bài Chủ Đề Khai Thác','Pioneer Day - Pacchetto Tema Estrazione Mineraria','Pioneer Day - Tematyczna Paczka Górnicza','يوم الرائد - حزمة التعدين الموضوعية','パイオニアデー - 採掘テーマカードパック','파이오니어 데이 - 채굴 테마 카드팩'],
 ['pioneer_fest_pack_mining_desc','打开即可获得2张3星及以上的「荒野掘金」游戏卡片。','Open to receive 2 "Wilderness Gold Rush" game cards of 3 stars or above.','Ouvrez pour recevoir 2 cartes de jeu "Ruée vers l\'Or Sauvage" de 3 étoiles ou plus.','Öffnen, um 2 "Wildnis-Goldrausch"-Spielkarten mit 3 Sternen oder mehr zu erhalten.','Abra para receber 2 cartas de jogo "Corrida do Ouro Selvagem" de 3 estrelas ou acima.','打開即可獲得2張3星及以上的「荒野掘金」遊戲卡片。','Buka untuk mendapatkan 2 kartu permainan "Demam Emas Liar" bintang 3 atau lebih.','เปิดเพื่อรับการ์ดเกม "ตื่นทองในดินแดนรกร้าง" 2 ใบ 3 ดาวขึ้นไป','Abre para recibir 2 cartas del juego "Fiebre del Oro Salvaje" de 3 estrellas o más.','Откройте, чтобы получить 2 игровые карточки «Золотая лихорадка» 3 звезды и выше.','Açarak "Vahşi Altın Akını" oyun kartlarından 3 yıldız veya daha fazla 2 adet alın.','Mở để nhận 2 thẻ bài "Cơn Sốt Vàng Hoang Dã" từ 3 sao trở lên.','Apri per ricevere 2 carte "Corsa all\'Oro Selvaggia" di 3 stelle o superiori.','Otwórz, aby otrzymać 2 karty "Gorączka Złota" o 3 gwiazdkach lub więcej.','افتح للحصول على بطاقتي لعبة "حمى الذهب البرية" من 3 نجوم أو أكثر.','開けると「荒野ゴールドラッシュ」ゲームカードが3★以上2枚もらえます。','열면 "황야의 골드러시" 게임 카드 3성 이상 2장을 받을 수 있습니다.'],
 ['pioneer_fest_pack_marble_name','拓荒节-弹珠主题卡包','Pioneer Day - Marble Theme Card Pack','Pioneer Day - Pack Thématique Billes','Pioneer Day - Murmel-Themenkartenpackung','Pioneer Day - Pacote Temático de Mármore','拓荒節-彈珠主題卡包','Pioneer Day - Paket Kartu Tema Kelereng','Pioneer Day - ชุดการ์ดธีมลูกแก้ว','Pioneer Day - Pack Temático de Canicas','Pioneer Day - Тематический набор «Мрамор»','Pioneer Day - Mermer Temalı Kart Paketi','Pioneer Day - Gói Bài Chủ Đề Bi','Pioneer Day - Pacchetto Tema Biglie','Pioneer Day - Tematyczna Paczka Kulkowa','يوم الرائد - حزمة الرخام الموضوعية','パイオニアデー - マーブルテーマカードパック','파이오니어 데이 - 구슬 테마 카드팩'],
 ['pioneer_fest_pack_marble_desc','打开即可获得2张3星及以上的「弹珠小游戏」游戏卡片。','Open to receive 2 "Marble Mini-Game" game cards of 3 stars or above.','Ouvrez pour recevoir 2 cartes de jeu "Mini-jeu de Billes" de 3 étoiles ou plus.','Öffnen, um 2 "Kugel-Mini-Spiel"-Spielkarten mit 3 Sternen oder mehr zu erhalten.','Abra para receber 2 cartas de jogo "Mini-Jogo de Mármore" de 3 estrelas ou acima.','打開即可獲得2張3星及以上的「彈珠小遊戲」遊戲卡片。','Buka untuk mendapatkan 2 kartu permainan "Mini Permainan Kelereng" bintang 3 atau lebih.','เปิดเพื่อรับการ์ดเกม "มินิเกมลูกแก้ว" 2 ใบ 3 ดาวขึ้นไป','Abre para recibir 2 cartas del juego "Minijuego de Canicas" de 3 estrellas o más.','Откройте, чтобы получить 2 карточки «Мини-игра в мрамор» 3 звезды и выше.','Açarak "Mermer Mini Oyunu" kartlarından 3 yıldız veya daha fazla 2 adet alın.','Mở để nhận 2 thẻ bài "Trò Chơi Bi Nhỏ" từ 3 sao trở lên.','Apri per ricevere 2 carte "Mini Gioco delle Biglie" di 3 stelle o superiori.','Otwórz, aby otrzymać 2 karty "Mini-Gra w Kulki" o 3 gwiazdkach lub więcej.','افتح للحصول على بطاقتي لعبة "الرخام الصغيرة" من 3 نجوم أو أكثر.','開けると「マーブルミニゲーム」ゲームカードが3★以上2枚もらえます。','열면 "구슬 미니게임" 게임 카드 3성 이상 2장을 받을 수 있습니다.'],
 ['pioneer_fest_pack_coin_pusher_name','拓荒节-推币机主题卡包','Pioneer Day - Coin Pusher Theme Card Pack','Pioneer Day - Pack Thématique Pousse-Pièces','Pioneer Day - Münzschieber-Themenkartenpackung','Pioneer Day - Pacote Temático Empurrador de Moedas','拓荒節-推幣機主題卡包','Pioneer Day - Paket Kartu Tema Mesin Pendorong Koin','Pioneer Day - ชุดการ์ดธีมเครื่องดันเหรียญ','Pioneer Day - Pack Temático Empujador de Monedas','Pioneer Day - Тематический набор «Монетный толкатель»','Pioneer Day - Para İtici Temalı Kart Paketi','Pioneer Day - Gói Bài Chủ Đề Máy Đẩy Xu','Pioneer Day - Pacchetto Tema Spingicoin','Pioneer Day - Tematyczna Paczka Popychacza Monet','يوم الرائد - حزمة دفع العملات الموضوعية','パイオニアデー - コインプッシャーテーマカードパック','파이오니어 데이 - 코인 푸셔 테마 카드팩'],
 ['pioneer_fest_pack_coin_pusher_desc','打开即可获得2张3星及以上的「推币机」游戏卡片。','Open to receive 2 "Coin Pusher" game cards of 3 stars or above.','Ouvrez pour recevoir 2 cartes de jeu "Pousse-Pièces" de 3 étoiles ou plus.','Öffnen, um 2 "Münzschieber"-Spielkarten mit 3 Sternen oder mehr zu erhalten.','Abra para receber 2 cartas de jogo "Empurrador de Moedas" de 3 estrelas ou acima.','打開即可獲得2張3星及以上的「推幣機」遊戲卡片。','Buka untuk mendapatkan 2 kartu permainan "Mesin Pendorong Koin" bintang 3 atau lebih.','เปิดเพื่อรับการ์ดเกม "เครื่องดันเหรียญ" 2 ใบ 3 ดาวขึ้นไป','Abre para recibir 2 cartas del juego "Empujador de Monedas" de 3 estrellas o más.','Откройте, чтобы получить 2 карточки «Монетный толкатель» 3 звезды и выше.','Açarak "Para İtici" oyun kartlarından 3 yıldız veya daha fazla 2 adet alın.','Mở để nhận 2 thẻ bài "Máy Đẩy Đồng Xu" từ 3 sao trở lên.','Apri per ricevere 2 carte "Spingicoin" di 3 stelle o superiori.','Otwórz, aby otrzymać 2 karty "Popychacz Monet" o 3 gwiazdkach lub więcej.','افتح للحصول على بطاقتي لعبة "دفع العملات" من 3 نجوم أو أكثر.','開けると「コインプッシャー」ゲームカードが3★以上2枚もらえます。','열면 "코인 푸셔" 게임 카드 3성 이상 2장을 받을 수 있습니다.'],
 ['pioneer_fest_pack_monopoly_name','拓荒节-拓荒大富翁主题卡包','Pioneer Day - Pioneer Monopoly Theme Card Pack','Pioneer Day - Pack Thématique Monopoly Pionnier','Pioneer Day - Pionier-Monopoly-Themenkartenpackung','Pioneer Day - Pacote Temático Monopólio Pioneiro','拓荒節-拓荒大富翁主題卡包','Pioneer Day - Paket Kartu Tema Monopoli Pionir','Pioneer Day - ชุดการ์ดธีมโมโนโพลีผู้บุกเบิก','Pioneer Day - Pack Temático Monopolio Pionero','Pioneer Day - Тематический набор «Монополия первопроходца»','Pioneer Day - Öncü Monopoly Temalı Kart Paketi','Pioneer Day - Gói Bài Chủ Đề Cờ Tỷ Phú','Pioneer Day - Pacchetto Tema Monopolio Pioniere','Pioneer Day - Tematyczna Paczka Monopoly Pionierów','يوم الرائد - حزمة الاحتكار الموضوعية','パイオニアデー - パイオニアモノポリーテーマカードパック','파이오니어 데이 - 파이오니어 모노폴리 테마 카드팩'],
 ['pioneer_fest_pack_monopoly_desc','打开即可获得2张3星及以上的「拓荒大富翁」游戏卡片。','Open to receive 2 "Pioneer Monopoly" game cards of 3 stars or above.','Ouvrez pour recevoir 2 cartes de jeu "Monopoly Pionnier" de 3 étoiles ou plus.','Öffnen, um 2 "Pionier-Monopoly"-Spielkarten mit 3 Sternen oder mehr zu erhalten.','Abra para receber 2 cartas de jogo "Monopólio Pioneiro" de 3 estrelas ou acima.','打開即可獲得2張3星及以上的「拓荒大富翁」遊戲卡片。','Buka untuk mendapatkan 2 kartu permainan "Monopoli Pionir" bintang 3 atau lebih.','เปิดเพื่อรับการ์ดเกม "โมโนโพลีผู้บุกเบิก" 2 ใบ 3 ดาวขึ้นไป','Abre para recibir 2 cartas del juego "Monopolio Pionero" de 3 estrellas o más.','Откройте, чтобы получить 2 карточки «Монополия первопроходца» 3 звезды и выше.','Açarak "Öncü Monopoly" oyun kartlarından 3 yıldız veya daha fazla 2 adet alın.','Mở để nhận 2 thẻ bài "Cờ Tỷ Phú Tiên Phong" từ 3 sao trở lên.','Apri per ricevere 2 carte "Monopolio Pioniere" di 3 stelle o superiori.','Otwórz, aby otrzymać 2 karty "Monopoly Pionierów" o 3 gwiazdkach lub więcej.','افتح للحصول على بطاقتي لعبة "احتكار الرائد" من 3 نجوم أو أكثر.','開けると「パイオニアモノポリー」ゲームカードが3★以上2枚もらえます。','열면 "파이오니어 모노폴리" 게임 카드 3성 이상 2장을 받을 수 있습니다.'],
 ['pioneer_fest_pack_common_name','拓荒节-白色保底卡包','Pioneer Day - Common Card Pack','Pioneer Day - Pack de Cartes Communes','Pioneer Day - Gewöhnliche Kartenpackung','Pioneer Day - Pacote de Cartas Comuns','拓荒節-白色保底卡包','Pioneer Day - Paket Kartu Umum','Pioneer Day - แพ็คการ์ดสามัญ','Pioneer Day - Pack de Cartas Comunes','Pioneer Day - Обычный набор карточек','Pioneer Day - Ortak Kart Paketi','Pioneer Day - Gói Bài Thường','Pioneer Day - Pacchetto Carte Comuni','Pioneer Day - Paczka Kart Pospolitych','يوم الرائد - حزمة البطاقات العادية','パイオニアデー - コモンカードパック','파이오니어 데이 - 일반 카드팩'],
 ['pioneer_fest_pack_common_desc','拓荒节卡包，至少含有1张普通品质或以上的卡片。','Pioneer Day card pack. Contains at least one card of Common quality or higher.','Pack de cartes Pioneer Day. Contient au moins une carte de qualité Commune ou supérieure.','Pioneer Day Kartenpackung. Enthält mindestens eine Karte der Qualität Gewöhnlich oder höher.','Pacote de cartas Pioneer Day. Contém pelo menos uma carta de qualidade Comum ou superior.','拓荒節卡包，至少含有1張普通品質或以上的卡片。','Paket kartu Pioneer Day. Berisi setidaknya satu kartu kualitas Umum atau lebih tinggi.','แพ็คการ์ดวันผู้บุกเบิก มีการ์ดคุณภาพสามัญอย่างน้อย 1 ใบ','Paquete de cartas Pioneer Day. Contiene al menos una carta de calidad Común o superior.','Набор карточек Pioneer Day. Содержит не менее одной карточки обычного качества или выше.','Pioneer Day kart paketi. En az bir Yaygın veya daha yüksek kaliteli kart içerir.','Gói bài Pioneer Day. Chứa ít nhất một lá bài chất lượng Thường trở lên.','Pacchetto carte Pioneer Day. Contiene almeno una carta di qualità Comune o superiore.','Paczka kart Pioneer Day. Zawiera co najmniej jedną kartę pospolitej jakości lub wyższej.','حزمة بطاقات يوم الرائد. تحتوي على بطاقة بجودة عادية أو أعلى.','パイオニアデーのカードパック。普通品質以上のカードが少なくとも1枚含まれています。','파이오니어 데이 카드팩. 일반 품질 이상의 카드 최소 1장 포함.'],
 ['pioneer_fest_pack_excellent_name','拓荒节-绿色保底卡包','Pioneer Day - Excellent Card Pack','Pioneer Day - Pack de Cartes Excellentes','Pioneer Day - Ausgezeichnete Kartenpackung','Pioneer Day - Pacote de Cartas Excelentes','拓荒節-綠色保底卡包','Pioneer Day - Paket Kartu Terbaik','Pioneer Day - แพ็คการ์ดยอดเยี่ยม','Pioneer Day - Pack de Cartas Excelentes','Pioneer Day - Отличный набор карточек','Pioneer Day - Mükemmel Kart Paketi','Pioneer Day - Gói Bài Xuất Sắc','Pioneer Day - Pacchetto Carte Eccellenti','Pioneer Day - Paczka Doskonałych Kart','يوم الرائد - حزمة البطاقات الممتازة','パイオニアデー - エクセレントカードパック','파이오니어 데이 - 우수 카드팩'],
 ['pioneer_fest_pack_excellent_desc','拓荒节卡包，至少含有1张优质品质或以上的卡片。','Pioneer Day card pack. Contains at least one card of Excellent quality or higher.','Pack de cartes Pioneer Day. Contient au moins une carte de qualité Excellente ou supérieure.','Pioneer Day Kartenpackung. Enthält mindestens eine Karte der Qualität Ausgezeichnet oder höher.','Pacote de cartas Pioneer Day. Contém pelo menos uma carta de qualidade Excelente ou superior.','拓荒節卡包，至少含有1張優質品質或以上的卡片。','Paket kartu Pioneer Day. Berisi setidaknya satu kartu kualitas Terbaik atau lebih tinggi.','แพ็คการ์ดวันผู้บุกเบิก มีการ์ดคุณภาพยอดเยี่ยมอย่างน้อย 1 ใบ','Paquete de cartas Pioneer Day. Contiene al menos una carta de calidad Excelente o superior.','Набор карточек Pioneer Day. Содержит не менее одной отличной карточки или выше.','Pioneer Day kart paketi. En az bir Mükemmel veya daha yüksek kaliteli kart içerir.','Gói bài Pioneer Day. Chứa ít nhất một lá bài chất lượng Xuất Sắc trở lên.','Pacchetto carte Pioneer Day. Contiene almeno una carta di qualità Eccellente o superiore.','Paczka kart Pioneer Day. Zawiera co najmniej jedną doskonałą kartę lub wyższą.','حزمة بطاقات يوم الرائد. تحتوي على بطاقة بجودة ممتازة أو أعلى.','パイオニアデーのカードパック。優質品質以上のカードが少なくとも1枚含まれています。','파이오니어 데이 카드팩. 우수 품질 이상의 카드 최소 1장 포함.'],
 ['pioneer_fest_pack_rare_name','拓荒节-蓝色保底卡包','Pioneer Day - Rare Card Pack','Pioneer Day - Pack de Cartes Rares','Pioneer Day - Seltene Kartenpackung','Pioneer Day - Pacote de Cartas Raras','拓荒節-藍色保底卡包','Pioneer Day - Paket Kartu Langka','Pioneer Day - แพ็คการ์ดหายาก','Pioneer Day - Pack de Cartas Raras','Pioneer Day - Редкий набор карточек','Pioneer Day - Nadir Kart Paketi','Pioneer Day - Gói Bài Hiếm','Pioneer Day - Pacchetto Carte Rare','Pioneer Day - Paczka Rzadkich Kart','يوم الرائد - حزمة البطاقات النادرة','パイオニアデー - レアカードパック','파이오니어 데이 - 레어 카드팩'],
 ['pioneer_fest_pack_rare_desc','拓荒节卡包，至少含有1张稀有品质或以上的卡片。','Pioneer Day card pack. Contains at least one card of Rare quality or higher.','Pack de cartes Pioneer Day. Contient au moins une carte de qualité Rare ou supérieure.','Pioneer Day Kartenpackung. Enthält mindestens eine Karte der Qualität Selten oder höher.','Pacote de cartas Pioneer Day. Contém pelo menos uma carta de qualidade Rara ou superior.','拓荒節卡包，至少含有1張稀有品質或以上的卡片。','Paket kartu Pioneer Day. Berisi setidaknya satu kartu kualitas Langka atau lebih tinggi.','แพ็คการ์ดวันผู้บุกเบิก มีการ์ดคุณภาพหายากอย่างน้อย 1 ใบ','Paquete de cartas Pioneer Day. Contiene al menos una carta de calidad Rara o superior.','Набор карточек Pioneer Day. Содержит не менее одной редкой карточки или выше.','Pioneer Day kart paketi. En az bir Nadir veya daha yüksek kaliteli kart içerir.','Gói bài Pioneer Day. Chứa ít nhất một lá bài chất lượng Hiếm trở lên.','Pacchetto carte Pioneer Day. Contiene almeno una carta di qualità Rara o superiore.','Paczka kart Pioneer Day. Zawiera co najmniej jedną rzadką kartę lub wyższą.','حزمة بطاقات يوم الرائد. تحتوي على بطاقة بجودة نادرة أو أعلى.','パイオニアデーのカードパック。稀有品質以上のカードが少なくとも1枚含まれています。','파이오니어 데이 카드팩. 희귀 품질 이상의 카드 최소 1장 포함.'],
 ['pioneer_fest_pack_epic_name','拓荒节-紫色保底卡包','Pioneer Day - Epic Card Pack','Pioneer Day - Pack de Cartes Épiques','Pioneer Day - Epische Kartenpackung','Pioneer Day - Pacote de Cartas Épicas','拓荒節-紫色保底卡包','Pioneer Day - Paket Kartu Epik','Pioneer Day - แพ็คการ์ดมหากาพย์','Pioneer Day - Pack de Cartas Épicas','Pioneer Day - Эпический набор карточек','Pioneer Day - Destansı Kart Paketi','Pioneer Day - Gói Bài Sử Thi','Pioneer Day - Pacchetto Carte Epiche','Pioneer Day - Paczka Epickich Kart','يوم الرائد - حزمة البطاقات الملحمية','パイオニアデー - エピックカードパック','파이오니어 데이 - 에픽 카드팩'],
 ['pioneer_fest_pack_epic_desc','拓荒节卡包，至少含有1张史诗品质或以上的卡片。','Pioneer Day card pack. Contains at least one card of Epic quality or higher.','Pack de cartes Pioneer Day. Contient au moins une carte de qualité Épique ou supérieure.','Pioneer Day Kartenpackung. Enthält mindestens eine Karte der Qualität Episch oder höher.','Pacote de cartas Pioneer Day. Contém pelo menos uma carta de qualidade Épica ou superior.','拓荒節卡包，至少含有1張史詩品質或以上的卡片。','Paket kartu Pioneer Day. Berisi setidaknya satu kartu kualitas Epik atau lebih tinggi.','แพ็คการ์ดวันผู้บุกเบิก มีการ์ดคุณภาพมหากาพย์อย่างน้อย 1 ใบ','Paquete de cartas Pioneer Day. Contiene al menos una carta de calidad Épica o superior.','Набор карточек Pioneer Day. Содержит не менее одной эпической карточки или выше.','Pioneer Day kart paketi. En az bir Destansı veya daha yüksek kaliteli kart içerir.','Gói bài Pioneer Day. Chứa ít nhất một lá bài chất lượng Sử Thi trở lên.','Pacchetto carte Pioneer Day. Contiene almeno una carta di qualità Epica o superiore.','Paczka kart Pioneer Day. Zawiera co najmniej jedną epicką kartę lub wyższą.','حزمة بطاقات يوم الرائد. تحتوي على بطاقة بجودة ملحمية أو أعلى.','パイオニアデーのカードパック。史詩品質以上のカードが少なくとも1枚含まれています。','파이오니어 데이 카드팩. 에픽 품질 이상의 카드 최소 1장 포함.'],
 ['pioneer_fest_pack_legendary_name','拓荒节-橙色保底卡包','Pioneer Day - Legendary Card Pack','Pioneer Day - Pack de Cartes Légendaires','Pioneer Day - Legendäre Kartenpackung','Pioneer Day - Pacote de Cartas Lendárias','拓荒節-橙色保底卡包','Pioneer Day - Paket Kartu Legendaris','Pioneer Day - แพ็คการ์ดตำนาน','Pioneer Day - Pack de Cartas Legendarias','Pioneer Day - Легендарный набор карточек','Pioneer Day - Efsanevi Kart Paketi','Pioneer Day - Gói Bài Huyền Thoại','Pioneer Day - Pacchetto Carte Leggendarie','Pioneer Day - Paczka Legendarnych Kart','يوم الرائد - حزمة البطاقات الأسطورية','パイオニアデー - レジェンダリーカードパック','파이오니어 데이 - 전설 카드팩'],
 ['pioneer_fest_pack_legendary_desc','拓荒节卡包，至少含有1张传说品质或以上的卡片。','Pioneer Day card pack. Contains at least one card of Legendary quality or higher.','Pack de cartes Pioneer Day. Contient au moins une carte de qualité Légendaire ou supérieure.','Pioneer Day Kartenpackung. Enthält mindestens eine Karte der Qualität Legendär oder höher.','Pacote de cartas Pioneer Day. Contém pelo menos uma carta de qualidade Lendária ou superior.','拓荒節卡包，至少含有1張傳說品質或以上的卡片。','Paket kartu Pioneer Day. Berisi setidaknya satu kartu kualitas Legendaris atau lebih tinggi.','แพ็คการ์ดวันผู้บุกเบิก มีการ์ดคุณภาพตำนานอย่างน้อย 1 ใบ','Paquete de cartas Pioneer Day. Contiene al menos una carta de calidad Legendaria o superior.','Набор карточек Pioneer Day. Содержит не менее одной легендарной карточки или выше.','Pioneer Day kart paketi. En az bir Efsanevi veya daha yüksek kaliteli kart içerir.','Gói bài Pioneer Day. Chứa ít nhất một lá bài chất lượng Huyền Thoại trở lên.','Pacchetto carte Pioneer Day. Contiene almeno una carta di qualità Leggendaria o superiore.','Paczka kart Pioneer Day. Zawiera co najmniej jedną legendarną kartę lub wyższą.','حزمة بطاقات يوم الرائد. تحتوي على بطاقة بجودة أسطورية أو أعلى.','パイオニアデーのカードパック。伝説品質以上のカードが少なくとも1枚含まれています。','파이오니어 데이 카드팩. 전설 품질 이상의 카드 최소 1장 포함.'],
 ['pioneer_fest_pack_selection_name','拓荒节-自选卡包','Pioneer Day - Custom Card Pack','Pioneer Day - Pack de Cartes Personnalisé','Pioneer Day - Angepasste Kartenpackung','Pioneer Day - Pacote de Cartas Personalizado','拓荒節-自選卡包','Pioneer Day - Paket Kartu Pilihan','Pioneer Day - แพ็คการ์ดเลือกเอง','Pioneer Day - Pack de Cartas Personalizado','Pioneer Day - Настраиваемый набор карточек','Pioneer Day - Özel Kart Paketi','Pioneer Day - Gói Bài Tự Chọn','Pioneer Day - Pacchetto Carte Personalizzato','Pioneer Day - Paczka Kart Niestandardowych','يوم الرائد - حزمة البطاقات المخصصة','パイオニアデー - カスタムカードパック','파이오니어 데이 - 커스텀 카드팩'],
 ['pioneer_fest_pack_selection_desc','工艺上乘的拓荒节自选卡包，可自选指定卡册中的传说、史诗品质卡片。','A premium Pioneer Day selection card pack. Choose any Legendary or Epic quality card from the designated collection.','Un pack de cartes Pioneer Day premium. Choisissez n\'importe quelle carte de qualité Légendaire ou Épique dans la collection désignée.','Ein erstklassiges Pioneer Day-Kartenpaket. Wählen Sie beliebige Karten der Qualität Legendär oder Episch aus der Sammlung.','Um pacote de cartas Pioneer Day premium. Escolha qualquer carta Lendária ou Épica da coleção designada.','工藝上乘的拓荒節自選卡包，可自選指定卡冊中的傳說、史詩品質卡片。','Paket kartu seleksi Pioneer Day premium. Pilih kartu Legendaris atau Epik dari koleksi yang ditentukan.','แพ็คการ์ดเลือกเองระดับพรีเมียมของวันผู้บุกเบิก เลือกการ์ดระดับตำนานหรือมหากาพย์จากคอลเลกชันที่กำหนด','Paquete de cartas de selección Pioneer Day premium. Elige cualquier carta de calidad Legendaria o Épica de la colección designada.','Премиальный выборочный набор карточек Pioneer Day. Выберите любую легендарную или эпическую карточку из указанной коллекции.','Premium Pioneer Day seçim kart paketi. Belirlenen koleksiyondan herhangi bir Efsanevi veya Destansı kart seçin.','Gói bài tự chọn Pioneer Day cao cấp. Chọn bất kỳ lá bài Huyền Thoại hoặc Sử Thi từ bộ sưu tập được chỉ định.','Pacchetto carte personalizzato Pioneer Day premium. Scegli qualsiasi carta di qualità Leggendaria o Epica dalla collezione designata.','Pakiet kart Pioneer Day premium. Wybierz dowolną Legendarną lub Epicką kartę z wyznaczonej kolekcji.','حزمة بطاقات مخصصة مميزة ليوم الرائد. اختر أي بطاقة أسطورية أو ملحمية من المجموعة المحددة.','プレミアムパイオニアデー自選カードパック。指定コレクションから伝説または史詩品質のカードをお好みで選べます。','프리미엄 파이오니어 데이 커스텀 카드팩. 지정 컬렉션에서 전설 또는 에픽 품질 카드를 자유 선택.'],
]

# ── BUILD ROWS ────────────────────────────────────────────────────────────────
def build_row(id_int, data_row):
    key = data_row[0]
    cn  = data_row[1]
    rest = data_row[2:]   # en, fr, de, po, zh, id, th, sp, ru, tr, vi, it, pl, ar, jp, kr
    cns = cn
    return [id_int, key, cn] + rest + [cns]

event_rows = []
idx = EVENT_START
for row in group_names:
    event_rows.append(build_row(idx, row)); idx += 1
for row in card_data:
    event_rows.append(build_row(idx, row)); idx += 1

item_rows = []
idx = ITEM_START
for row in item_data:
    item_rows.append(build_row(idx, row)); idx += 1

print(f"EVENT rows: {len(event_rows)}, ITEM rows: {len(item_rows)}")

# ── WRITE ─────────────────────────────────────────────────────────────────────
def gws_append(tab, rows):
    args_dict = {
        'args': ['sheets', 'spreadsheets', 'values', 'append',
            '--params', json.dumps({
                'spreadsheetId': SHEET,
                'range': f"'{tab}'!A1",
                'valueInputOption': 'RAW',
                'insertDataOption': 'INSERT_ROWS',
            }),
        ],
        'json': {'values': rows}
    }
    inp = json.dumps(args_dict, ensure_ascii=False).encode('utf-8')
    r = subprocess.run(
        ['node', r'C:\ADHD_agent\scripts\gws_stdin.js'],
        input=inp, capture_output=True, timeout=120
    )
    raw = r.stdout.decode('utf-8', errors='replace')
    result = json.loads(raw)
    upd = result.get('updates', {})
    print(f"  OK {tab}: wrote {upd.get('updatedRows')} rows to {upd.get('updatedRange')}")
    return result

print("Writing EVENT tab...")
gws_append('EVENT', event_rows)
print("Writing ITEM tab...")
gws_append('ITEM', item_rows)
print("Done.")
